<script setup lang="ts">
import { computed, ref } from 'vue'
import { Check } from 'lucide-vue-next'
import type { PeriodRecord, ScheduleSlot } from '../../types/legacy'

const days=['Thứ 2','Thứ 3','Thứ 4','Thứ 5','Thứ 6']
const props=withDefaults(defineProps<{modelValue:ScheduleSlot[];periods:PeriodRecord[];dayPeriods?:Record<number,PeriodRecord[]>;disabled?:boolean;readOnly?:boolean}>(),{disabled:false,readOnly:false,dayPeriods:()=>({})})
const emit=defineEmits<{'update:modelValue':[value:ScheduleSlot[]]}>()
const currentDay=new Date().getDay();const activeDay=ref(currentDay>=1&&currentDay<=5?currentDay-1:0)
const selected=computed(()=>new Set(props.modelValue.map(slot=>`${slot.dow}-${slot.period}`)))
const rowNumbers=computed(()=>{const values=new Set<number>(props.periods.map(row=>row.n));for(const rows of Object.values(props.dayPeriods))for(const row of rows)values.add(row.n);return [...values].sort((a,b)=>a-b)})
const mobilePeriods=computed(()=>props.dayPeriods[activeDay.value]?.length?props.dayPeriods[activeDay.value]:props.periods)
function periodForDay(dow:number,n:number){return (props.dayPeriods[dow]?.length?props.dayPeriods[dow]:props.periods).find(row=>row.n===n)??null}
function isSelected(dow:number,period:number){return selected.value.has(`${dow}-${period}`)}
function toggle(dow:number,period:number){if(props.disabled||props.readOnly||!periodForDay(dow,period))return;const key=`${dow}-${period}`,next=props.modelValue.filter(slot=>`${slot.dow}-${slot.period}`!==key);if(!selected.value.has(key))next.push({dow,period});emit('update:modelValue',next.sort((a,b)=>a.dow-b.dow||a.period-b.period))}
function slotLabel(dow:number,n:number){const period=periodForDay(dow,n);return period?`${days[dow]}, Tiết ${n}, ${period.start}–${period.end}`:`${days[dow]}, Tiết ${n} không có trong mẫu TKB`}
function sameTime(n:number){const rows=days.map((_,dow)=>periodForDay(dow,n)).filter(Boolean) as PeriodRecord[];if(!rows.length)return'';return rows.every(row=>row.start===rows[0].start&&row.end===rows[0].end)?`${rows[0].start}–${rows[0].end}`:'Theo ngày'}
</script>
<template>
  <div class="schedule-grid-shell" :class="{readonly:readOnly}">
    <div class="desktop-schedule" role="grid" aria-label="Thời khóa biểu tự học">
      <div class="corner" role="columnheader">Tiết học</div><div v-for="day in days" :key="day" class="day-head" role="columnheader">{{ day }}</div>
      <template v-for="n in rowNumbers" :key="n"><div class="period-head" role="rowheader"><b>Tiết {{ n }}</b><span>{{ sameTime(n) }}</span></div><button v-for="(_,dow) in days" :key="`${dow}-${n}`" type="button" class="slot-button" :class="{selected:isSelected(dow,n),unavailable:!periodForDay(dow,n)}" :aria-label="slotLabel(dow,n)" :aria-pressed="isSelected(dow,n)" :disabled="disabled||readOnly||!periodForDay(dow,n)" role="gridcell" @click="toggle(dow,n)"><template v-if="periodForDay(dow,n)"><small>{{ periodForDay(dow,n)?.start }}–{{ periodForDay(dow,n)?.end }}</small><span class="slot-state"><Check v-if="isSelected(dow,n)"/>{{ isSelected(dow,n)?'Tự học':'' }}</span></template><span v-else>—</span></button></template>
    </div>
    <div class="mobile-schedule"><div class="mobile-day-tabs" role="tablist"><button v-for="(day,dow) in days" :key="day" type="button" role="tab" :aria-selected="activeDay===dow" :class="{active:activeDay===dow}" @click="activeDay=dow">{{ day }}</button></div><div class="mobile-periods"><button v-for="period in mobilePeriods" :key="period.n" type="button" class="mobile-period" :class="{selected:isSelected(activeDay,period.n)}" :disabled="disabled||readOnly" @click="toggle(activeDay,period.n)"><span><b>Tiết {{ period.n }}</b><small>{{ period.start }}–{{ period.end }}</small></span><span class="mobile-state"><Check v-if="isSelected(activeDay,period.n)"/>{{ isSelected(activeDay,period.n)?'Tự học':'' }}</span></button></div></div>
  </div>
</template>
<style scoped>
.desktop-schedule{display:grid;grid-template-columns:minmax(116px,.75fr) repeat(5,minmax(105px,1fr));gap:8px;min-width:720px}.corner,.day-head,.period-head{display:flex;align-items:center;justify-content:center;min-height:48px;border-radius:12px;background:var(--surface-soft);color:var(--text-muted);font-weight:800}.period-head{align-items:flex-start;flex-direction:column;padding:8px 12px}.period-head span{font-size:var(--font-size-ui-min);font-weight:600}.slot-button{min-height:64px;display:grid;place-items:center;gap:3px;border:1px solid var(--border);border-radius:12px;background:var(--surface);color:var(--text-muted);font-weight:750}.slot-button small{font-size:var(--font-size-ui-min)}.slot-state{display:flex;align-items:center;gap:5px}.slot-button.selected{border-color:color-mix(in srgb,var(--color-mint) 72%,var(--color-primary));background:linear-gradient(145deg,var(--wash-mint),color-mix(in srgb,var(--wash-sky) 55%,var(--surface)));color:var(--color-success)}.slot-button.unavailable{opacity:.35}.slot-button svg{width:16px}.readonly .slot-button.selected{cursor:default}.mobile-schedule{display:none}.mobile-day-tabs{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:4px;padding:4px;border-radius:12px;background:var(--surface-soft)}.mobile-day-tabs button{min-height:44px;border:0;border-radius:9px;background:transparent;color:var(--text-muted);font-weight:800}.mobile-day-tabs button.active{background:var(--surface);color:var(--color-primary)}.mobile-periods{display:grid;gap:8px;margin-top:12px}.mobile-period{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px;border:1px solid var(--border);border-radius:12px;background:var(--surface);color:var(--text);text-align:left}.mobile-period>span:first-child{display:grid}.mobile-period small{color:var(--text-muted)}.mobile-period.selected{background:var(--wash-mint);border-color:color-mix(in srgb,var(--color-mint) 72%,var(--color-primary))}.mobile-state{display:flex;gap:4px;align-items:center}.mobile-state svg{width:16px}@media(max-width:900px){.desktop-schedule{display:none}.mobile-schedule{display:block}}
</style>
