-- SỔ TỰ HỌC V8.3.0 — CANONICAL FRESH INSTALL ONLY
-- CHỈ DÙNG CHO DỰ ÁN SUPABASE MỚI, TRỐNG.
-- Cơ sở dữ liệu V8.2.5 đang hoạt động chỉ chạy PATCH-V830-CUMULATIVE-FROM-V825.sql.

-- SỔ TỰ HỌC - Supabase/PostgreSQL schema
-- Chạy trong Supabase SQL Editor.
create extension if not exists pgcrypto;

do $$ begin
  create type public.app_role as enum ('student','monitor','teacher');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.registration_status as enum ('draft','submitted','needs_revision','approved');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.week_status as enum ('upcoming','open','locked','holiday');
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  student_code text unique,
  full_name text not null,
  email text,
  role public.app_role not null default 'student',
  class_name text default '10A1',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.school_years (
  id uuid primary key default gen_random_uuid (),
  name text not null unique,
  start_date date not null,
  end_date date not null,
  is_active boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.weeks (
  id uuid primary key default gen_random_uuid (),
  school_year_id uuid not null references public.school_years (id) on delete cascade,
  week_number int not null check (week_number > 0),
  start_date date not null,
  end_date date not null,
  status public.week_status not null default 'upcoming',
  registration_deadline timestamptz,
  note text,
  unique (school_year_id, week_number)
);

create table if not exists public.periods (
  period_number int primary key check (period_number between 1 and 9),
  start_time time not null,
  end_time time not null
);

insert into
  public.periods (period_number, start_time, end_time)
values
  (1, '07:40', '08:20'),
  (2, '08:25', '09:05'),
  (3, '09:20', '10:00'),
  (4, '10:05', '10:45'),
  (5, '10:50', '11:30'),
  (6, '13:15', '13:55'),
  (7, '14:00', '14:40'),
  (8, '14:55', '15:35'),
  (9, '15:40', '16:20')
on conflict (period_number) do update
set
  start_time = excluded.start_time,
  end_time = excluded.end_time;

create table if not exists public.study_schedule (
  id uuid primary key default gen_random_uuid (),
  weekday int not null check (weekday between 1 and 5), -- 1=Thứ 2 ... 5=Thứ 6
  period_number int not null references public.periods (period_number),
  is_study_period boolean not null default true,
  unique (weekday, period_number)
);

create table if not exists public.week_schedule_overrides (
  id uuid primary key default gen_random_uuid (),
  week_id uuid not null references public.weeks (id) on delete cascade,
  weekday int not null check (weekday between 1 and 5),
  period_number int not null references public.periods (period_number),
  is_study_period boolean not null default true,
  reason text,
  unique (week_id, weekday, period_number)
);

create table if not exists public.registrations (
  id uuid primary key default gen_random_uuid (),
  student_id uuid not null references public.profiles (id) on delete cascade,
  week_id uuid not null references public.weeks (id) on delete cascade,
  weekday int not null check (weekday between 1 and 5),
  period_number int not null references public.periods (period_number),
  content text not null check (length(content) between 1 and 500),
  note text,
  status public.registration_status not null default 'draft',
  teacher_comment text,
  submitted_at timestamptz,
  updated_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by uuid references public.profiles (id),
  is_deleted boolean not null default false,
  deleted_at timestamptz,
  deleted_by uuid references public.profiles (id),
  unique (student_id, week_id, weekday, period_number)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles (id),
  action text not null,
  entity_type text not null,
  entity_id text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

-- Tự tạo profile cơ bản khi user Auth được tạo.
create or replace function public.handle_new_user () returns trigger language plpgsql security definer
set
  search_path = public as $$
begin
  insert into public.profiles(id,full_name,email)
  values(new.id,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),new.email)
  on conflict(id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users for each row
execute procedure public.handle_new_user ();

-- Helper role functions, SECURITY DEFINER để tránh policy recursion.
create or replace function public.current_app_role () returns public.app_role language sql stable security definer
set
  search_path = public as $$ select role from public.profiles where id = auth.uid() and active = true $$;

create or replace function public.is_teacher () returns boolean language sql stable security definer
set
  search_path = public as $$ select coalesce(public.current_app_role() = 'teacher', false) $$;

create or replace function public.can_view_class () returns boolean language sql stable security definer
set
  search_path = public as $$ select coalesce(public.current_app_role() in ('monitor','teacher'), false) $$;

create or replace function public.current_app_class () returns text language sql stable security definer
set
  search_path = public as $$
  select class_name
  from public.profiles
  where id = auth.uid() and active = true
$$;

create or replace function public.can_view_student (target_student_id uuid) returns boolean language sql stable security definer
set
  search_path = public as $$
  select
    public.is_teacher()
    or (
      public.current_app_role() = 'monitor'
      and exists (
        select 1
        from public.profiles target
        where target.id = target_student_id
          and target.class_name = public.current_app_class()
      )
    )
$$;

-- Safe member directory. security_invoker buộc view tuân theo RLS của profiles.
drop view if exists public.class_members;

create view public.class_members
with
  (security_invoker = on) as
select
  id,
  student_code,
  full_name,
  role,
  class_name,
  active
from
  public.profiles
where
  id = auth.uid ()
  or public.is_teacher ()
  or (
    public.current_app_role () = 'monitor'
    and class_name = public.current_app_class ()
  );

revoke all on public.class_members
from
  anon;

revoke all on public.class_members
from
  authenticated;

grant
select
  on public.class_members to authenticated;

-- RLS
alter table public.profiles enable row level security;

alter table public.school_years enable row level security;

alter table public.weeks enable row level security;

alter table public.periods enable row level security;

alter table public.study_schedule enable row level security;

alter table public.week_schedule_overrides enable row level security;

alter table public.registrations enable row level security;

alter table public.audit_logs enable row level security;

alter table public.app_settings enable row level security;

-- profiles
-- Chỉ cho frontend đọc các cột an toàn; email nội bộ không được cấp SELECT.
revoke all on public.profiles
from
  anon;

revoke
select
  on public.profiles
from
  authenticated;

grant
select
  (
    id,
    student_code,
    full_name,
    role,
    class_name,
    active
  ) on public.profiles to authenticated;

drop policy if exists profiles_select on public.profiles;

create policy profiles_select on public.profiles for
select
  to authenticated using (
    id = auth.uid ()
    or public.is_teacher ()
    or (
      public.current_app_role () = 'monitor'
      and class_name = public.current_app_class ()
    )
  );

-- Việc sửa tài khoản đi qua Edge Function admin-update-user.
revoke
update on public.profiles
from
  authenticated;

drop policy if exists profiles_teacher_update on public.profiles;

-- common read-only configuration
drop policy if exists school_years_read on public.school_years;

create policy school_years_read on public.school_years for
select
  to authenticated using (true);

drop policy if exists weeks_read on public.weeks;

create policy weeks_read on public.weeks for
select
  to authenticated using (true);

drop policy if exists periods_read on public.periods;

create policy periods_read on public.periods for
select
  to authenticated using (true);

drop policy if exists schedule_read on public.study_schedule;

create policy schedule_read on public.study_schedule for
select
  to authenticated using (true);

drop policy if exists overrides_read on public.week_schedule_overrides;

create policy overrides_read on public.week_schedule_overrides for
select
  to authenticated using (true);

drop policy if exists settings_read on public.app_settings;

create policy settings_read on public.app_settings for
select
  to authenticated using (true);

-- teacher manages configuration
drop policy if exists school_years_teacher_all on public.school_years;

create policy school_years_teacher_all on public.school_years for all to authenticated using (public.is_teacher ())
with
  check (public.is_teacher ());

drop policy if exists weeks_teacher_all on public.weeks;

create policy weeks_teacher_all on public.weeks for all to authenticated using (public.is_teacher ())
with
  check (public.is_teacher ());

drop policy if exists periods_teacher_all on public.periods;

create policy periods_teacher_all on public.periods for all to authenticated using (public.is_teacher ())
with
  check (public.is_teacher ());

drop policy if exists schedule_teacher_all on public.study_schedule;

create policy schedule_teacher_all on public.study_schedule for all to authenticated using (public.is_teacher ())
with
  check (public.is_teacher ());

drop policy if exists overrides_teacher_all on public.week_schedule_overrides;

create policy overrides_teacher_all on public.week_schedule_overrides for all to authenticated using (public.is_teacher ())
with
  check (public.is_teacher ());

drop policy if exists settings_teacher_all on public.app_settings;

create policy settings_teacher_all on public.app_settings for all to authenticated using (public.is_teacher ())
with
  check (public.is_teacher ());

-- registrations: HS tự đọc/ghi của mình, cán sự & GV đọc cả lớp, GV quản trị.
drop policy if exists registrations_select on public.registrations;

create policy registrations_select on public.registrations for
select
  to authenticated using (
    (
      student_id = auth.uid ()
      and is_deleted = false
    )
    or (
      is_deleted = false
      and public.can_view_student (student_id)
    )
  );

drop policy if exists registrations_student_insert on public.registrations;

create policy registrations_student_insert on public.registrations for insert to authenticated
with
  check (
    student_id = auth.uid ()
    and status in ('draft', 'submitted')
    and exists (
      select
        1
      from
        public.weeks w
      where
        w.id = week_id
        and w.status = 'open'
        and (
          w.registration_deadline is null
          or now() <= w.registration_deadline
        )
    )
  );

drop policy if exists registrations_student_update on public.registrations;

create policy registrations_student_update on public.registrations
for update
  to authenticated using (
    student_id = auth.uid ()
    and is_deleted = false
    and status in ('draft', 'submitted', 'needs_revision')
    and exists (
      select
        1
      from
        public.weeks w
      where
        w.id = week_id
        and w.status = 'open'
        and (
          w.registration_deadline is null
          or now() <= w.registration_deadline
          or registrations.status = 'needs_revision'
        )
    )
  )
with
  check (
    student_id = auth.uid ()
    and status in ('draft', 'submitted')
  );

drop policy if exists registrations_teacher_update on public.registrations;

create policy registrations_teacher_update on public.registrations
for update
  to authenticated using (public.is_teacher ())
with
  check (public.is_teacher ());

-- Không cấp DELETE cho frontend; GV dùng soft delete qua UPDATE.
drop policy if exists audit_teacher_select on public.audit_logs;

create policy audit_teacher_select on public.audit_logs for
select
  to authenticated using (public.is_teacher ());

drop policy if exists audit_authenticated_insert on public.audit_logs;

create policy audit_authenticated_insert on public.audit_logs for insert to authenticated
with
  check (actor_id = auth.uid ());

-- Indexes
create index if not exists idx_registrations_week on public.registrations (week_id);

create index if not exists idx_registrations_student on public.registrations (student_id);

create index if not exists idx_registrations_status on public.registrations (status);

create index if not exists idx_weeks_school_year on public.weeks (school_year_id, week_number);

-- =========================
-- V5: deadline modes + smart approval + teacher notifications
-- =========================
-- SỔ TỰ HỌC V5
-- 1) Deadline độc lập theo từng tuần:
--    per_session_20  = 20:00 tối hôm trước TỪNG BUỔI
--    week_before_20  = 20:00 ngày trước khi tuần bắt đầu
--    specific        = hạn ngày/giờ cụ thể do GV chọn
-- 2) Duyệt nhanh thông minh theo quy tắc bảo thủ.
-- 3) Tạo thông báo cho GV khi nội dung cần duyệt thủ công.
--
-- Chạy MỘT LẦN trong Supabase SQL Editor sau patch V3/V4.
do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema='public'
      and table_name='weeks'
      and column_name='deadline_mode'
  ) then
    alter table public.weeks
      add column deadline_mode text not null default 'week_before_20';

    -- Bảo toàn hành vi V4: deadline đang có được coi là "hạn cụ thể"
    -- cho tới khi GV chủ động đổi chế độ của tuần đó.
    update public.weeks
    set deadline_mode='specific'
    where registration_deadline is not null;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'weeks_deadline_mode_check'
      and conrelid = 'public.weeks'::regclass
  ) then
    alter table public.weeks
      add constraint weeks_deadline_mode_check
      check (deadline_mode in ('per_session_20','week_before_20','specific'));
  end if;
end $$;

alter table public.registrations
add column if not exists approval_source text not null default 'manual';

alter table public.registrations
add column if not exists auto_review_reason text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'registrations_approval_source_check'
      and conrelid = 'public.registrations'::regclass
  ) then
    alter table public.registrations
      add constraint registrations_approval_source_check
      check (approval_source in ('manual','auto_rule'));
  end if;
end $$;

-- Deadline thực tế của một tiết.
-- p_weekday: 1=Thứ 2 ... 5=Thứ 6.
create or replace function public.registration_deadline_for_slot (p_week_id uuid, p_weekday int) returns timestamptz language sql stable security definer
set
  search_path = public as $$
  select
    case w.deadline_mode
      when 'per_session_20' then
        (
          (
            w.start_date
            + (greatest(1, least(5, p_weekday)) - 1)
            - 1
          )::timestamp
          + time '20:00'
        ) at time zone 'Asia/Ho_Chi_Minh'
      when 'week_before_20' then
        (
          (w.start_date - 1)::timestamp
          + time '20:00'
        ) at time zone 'Asia/Ho_Chi_Minh'
      when 'specific' then
        w.registration_deadline
      else
        w.registration_deadline
    end
  from public.weeks w
  where w.id = p_week_id
$$;

create or replace function public.smart_approval_is_enabled () returns boolean language sql stable security definer
set
  search_path = public as $$
  select coalesce(
    (select value = 'true'::jsonb from public.app_settings where key='smart_approval_enabled'),
    true
  )
$$;

-- RLS: deadline tính theo đúng chế độ của từng tuần/tiết.
-- Bật duyệt nhanh mặc định. GV có thể tắt trong Cài đặt.
insert into
  public.app_settings (key, value)
values
  ('smart_approval_enabled', 'true'::jsonb)
on conflict (key) do nothing;

-- Bảng thông báo riêng cho GV.
create table if not exists public.teacher_notifications (
  id uuid primary key default gen_random_uuid (),
  registration_id uuid not null references public.registrations (id) on delete cascade,
  student_id uuid not null references public.profiles (id) on delete cascade,
  week_id uuid not null references public.weeks (id) on delete cascade,
  notification_type text not null default 'manual_review',
  title text not null,
  message text,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  unique (registration_id, notification_type)
);

alter table public.teacher_notifications enable row level security;

drop policy if exists teacher_notifications_select on public.teacher_notifications;

create policy teacher_notifications_select on public.teacher_notifications for
select
  to authenticated using (public.is_teacher ());

drop policy if exists teacher_notifications_update on public.teacher_notifications;

create policy teacher_notifications_update on public.teacher_notifications
for update
  to authenticated using (public.is_teacher ())
with
  check (public.is_teacher ());

drop policy if exists teacher_notifications_delete on public.teacher_notifications;

create policy teacher_notifications_delete on public.teacher_notifications for delete to authenticated using (public.is_teacher ());

create index if not exists idx_teacher_notifications_unread on public.teacher_notifications (is_read, created_at desc);

revoke all on public.teacher_notifications
from
  anon;

grant
select
,
update,
delete on public.teacher_notifications to authenticated;

-- Phân loại bảo thủ:
-- - Có tín hiệu giải trí / mạng xã hội => GV duyệt.
-- - Có tín hiệu học tập rõ ràng => tự duyệt.
-- - Thiết bị điện tử chỉ tự duyệt khi đi kèm mục đích học.
-- - Còn lại => GV duyệt.
create or replace function public.smart_review_registration (p_content text, p_note text) returns table (auto_approve boolean, reason text) language plpgsql stable security definer
set
  search_path = public as $$
declare
  v_text text := lower(coalesce(p_content,'') || ' ' || coalesce(p_note,''));
  v_has_study boolean;
  v_has_device boolean;
  v_has_nonstudy boolean;
begin
  v_has_nonstudy :=
    v_text ~ '(chơi[[:space:]]*game|game[[:space:]]*giải[[:space:]]*trí|tiktok|facebook|instagram|xem[[:space:]]*phim|video[[:space:]]*giải[[:space:]]*trí|nghe[[:space:]]*nhạc|mạng[[:space:]]*xã[[:space:]]*hội|lướt[[:space:]]*mạng|chat|nhắn[[:space:]]*tin|giải[[:space:]]*trí|shopping|mua[[:space:]]*sắm)';

  v_has_device :=
    v_text ~ '(điện[[:space:]]*thoại|laptop|máy[[:space:]]*tính|tablet|ipad|chromebook|thiết[[:space:]]*bị[[:space:]]*điện[[:space:]]*tử|internet|website|youtube|ứng[[:space:]]*dụng|app)';

  v_has_study :=
    v_text ~ '(học|ôn|ôn[[:space:]]*tập|bài[[:space:]]*tập|làm[[:space:]]*bài|đọc[[:space:]]*sách|soạn[[:space:]]*bài|luyện|làm[[:space:]]*đề|đề[[:space:]]*kiểm[[:space:]]*tra|nghiên[[:space:]]*cứu|tra[[:space:]]*cứu|tìm[[:space:]]*tài[[:space:]]*liệu|ghi[[:space:]]*chép|thuyết[[:space:]]*trình|dự[[:space:]]*án|lập[[:space:]]*trình|coding|programming|bài[[:space:]]*giảng|từ[[:space:]]*vựng|công[[:space:]]*thức|sgk|sách[[:space:]]*giáo[[:space:]]*khoa|kiểm[[:space:]]*tra|study|homework|research|practice|toán|ngữ[[:space:]]*văn|văn[[:space:]]*học|tiếng[[:space:]]*anh|anh[[:space:]]*văn|vật[[:space:]]*lí|vật[[:space:]]*lý|hóa[[:space:]]*học|hoá[[:space:]]*học|sinh[[:space:]]*học|lịch[[:space:]]*sử|địa[[:space:]]*lí|địa[[:space:]]*lý|tin[[:space:]]*học|công[[:space:]]*nghệ|giáo[[:space:]]*dục)';

  if v_has_nonstudy then
    return query select false, 'Có dấu hiệu giải trí/mạng xã hội; cần giáo viên xác nhận.';
    return;
  end if;

  if v_has_device and v_has_study then
    return query select true, 'Thiết bị điện tử được nêu kèm mục đích học tập rõ ràng.';
    return;
  end if;

  if v_has_study and not v_has_device then
    return query select true, 'Nội dung học tập rõ ràng.';
    return;
  end if;

  if v_has_device and not v_has_study then
    return query select false, 'Có sử dụng thiết bị điện tử nhưng mục đích học tập chưa đủ rõ.';
    return;
  end if;

  return query select false, 'Nội dung chưa đủ rõ để tự động duyệt.';
end;
$$;

-- RLS: deadline + duyệt tự động sau BEFORE trigger.
drop policy if exists registrations_student_insert on public.registrations;

create policy registrations_student_insert on public.registrations for insert to authenticated
with
  check (
    student_id = auth.uid ()
    and (
      status in ('draft', 'submitted')
      or (
        status = 'approved'
        and approval_source = 'auto_rule'
        and public.smart_approval_is_enabled ()
        and exists (
          select
            1
          from
            public.smart_review_registration (content, note) s
          where
            s.auto_approve = true
        )
      )
    )
    and exists (
      select
        1
      from
        public.weeks w
      where
        w.id = week_id
        and w.status = 'open'
        and (
          public.registration_deadline_for_slot (week_id, weekday) is null
          or now() <= public.registration_deadline_for_slot (week_id, weekday)
        )
    )
  );

drop policy if exists registrations_student_update on public.registrations;

create policy registrations_student_update on public.registrations
for update
  to authenticated using (
    student_id = auth.uid ()
    and is_deleted = false
    and status in ('draft', 'submitted', 'needs_revision')
    and exists (
      select
        1
      from
        public.weeks w
      where
        w.id = week_id
        and w.status = 'open'
        and (
          public.registration_deadline_for_slot (week_id, weekday) is null
          or now() <= public.registration_deadline_for_slot (week_id, weekday)
          or registrations.status = 'needs_revision'
        )
    )
  )
with
  check (
    student_id = auth.uid ()
    and (
      status in ('draft', 'submitted')
      or (
        status = 'approved'
        and approval_source = 'auto_rule'
        and public.smart_approval_is_enabled ()
        and exists (
          select
            1
          from
            public.smart_review_registration (content, note) s
          where
            s.auto_approve = true
        )
      )
    )
  );

-- BEFORE trigger: tự duyệt khi quy tắc cho phép.
create or replace function public.apply_smart_approval () returns trigger language plpgsql security definer
set
  search_path = public as $$
declare
  v_enabled boolean := public.smart_approval_is_enabled();
  v_auto boolean := false;
  v_reason text := null;
  v_should_review boolean := false;
begin
  -- HS không thể tự gán "approved". Nếu cố gán, đưa về submitted rồi phân loại lại.
  if auth.uid() = new.student_id and new.status = 'approved' then
    new.status := 'submitted';
    new.approval_source := 'manual';
    new.approved_at := null;
    new.approved_by := null;
  end if;

  if new.status = 'submitted' then
    if tg_op = 'INSERT' then
      v_should_review := true;
    elsif old.status is distinct from 'submitted'
       or old.content is distinct from new.content
       or old.note is distinct from new.note then
      v_should_review := true;
    end if;
  end if;

  if v_should_review then
    if v_enabled then
      select s.auto_approve, s.reason
      into v_auto, v_reason
      from public.smart_review_registration(new.content,new.note) s;

      new.auto_review_reason := v_reason;

      if coalesce(v_auto,false) then
        new.status := 'approved';
        new.approval_source := 'auto_rule';
        new.approved_at := now();
        new.approved_by := null;
      else
        new.status := 'submitted';
        new.approval_source := 'manual';
        new.approved_at := null;
        new.approved_by := null;
      end if;
    else
      new.status := 'submitted';
      new.approval_source := 'manual';
      new.auto_review_reason := 'Duyệt nhanh thông minh đang tắt.';
      new.approved_at := null;
      new.approved_by := null;
    end if;
  elsif new.status = 'approved' and auth.uid() is distinct from new.student_id then
    -- Phê duyệt thủ công của GV.
    if new.approval_source <> 'auto_rule' then
      new.approval_source := 'manual';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_apply_smart_approval on public.registrations;

create trigger trg_apply_smart_approval before insert
or
update of status,
content,
note on public.registrations for each row
execute function public.apply_smart_approval ();

-- AFTER trigger: nội dung cần GV duyệt => tạo/đánh thức thông báo.
create or replace function public.sync_teacher_review_notification () returns trigger language plpgsql security definer
set
  search_path = public as $$
declare
  v_student_name text;
begin
  select full_name into v_student_name
  from public.profiles
  where id = new.student_id;

  if new.status = 'submitted' and new.approval_source = 'manual' then
    insert into public.teacher_notifications(
      registration_id,student_id,week_id,notification_type,title,message,is_read,created_at
    )
    values(
      new.id,
      new.student_id,
      new.week_id,
      'manual_review',
      'Đăng ký cần giáo viên duyệt',
      coalesce(v_student_name,'Học sinh') || ': ' ||
        left(coalesce(new.content,''),160) ||
        case
          when new.auto_review_reason is not null
          then ' — ' || new.auto_review_reason
          else ''
        end,
      false,
      now()
    )
    on conflict (registration_id,notification_type)
    do update set
      title = excluded.title,
      message = excluded.message,
      is_read = false,
      created_at = now();
  else
    update public.teacher_notifications
    set is_read = true
    where registration_id = new.id
      and notification_type = 'manual_review'
      and is_read = false;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_sync_teacher_review_notification on public.registrations;

create trigger trg_sync_teacher_review_notification
after insert
or
update of status,
content,
note on public.registrations for each row
execute function public.sync_teacher_review_notification ();

-- Các đăng ký cũ đang chờ duyệt không tự động đổi trạng thái.
-- Chúng chỉ được phân loại lại khi HS gửi/cập nhật lần tiếp theo.
-- Đăng ký cũ đang "submitted" được đưa vào chuông GV để không bị bỏ sót.
-- Không tự duyệt hồi tố: GV vẫn quyết định các bản ghi đã tồn tại trước V5.
insert into
  public.teacher_notifications (
    registration_id,
    student_id,
    week_id,
    notification_type,
    title,
    message,
    is_read,
    created_at
  )
select
  r.id,
  r.student_id,
  r.week_id,
  'manual_review',
  'Đăng ký cũ cần giáo viên duyệt',
  coalesce(p.full_name, 'Học sinh') || ': ' || left(coalesce(r.content, ''), 160),
  false,
  now()
from
  public.registrations r
  left join public.profiles p on p.id = r.student_id
where
  r.status = 'submitted'
  and r.is_deleted = false
on conflict (registration_id, notification_type) do nothing;

-- =========================
-- V6: safe account deletion / active-session RLS
-- =========================
-- SỔ TỰ HỌC V6 — KHÓA QUYỀN NGAY KHI XÓA TÀI KHOẢN
-- Chạy MỘT LẦN sau PATCH-V5.
--
-- admin-delete-user sẽ:
-- 1) set profiles.active=false;
-- 2) đổi student_code sang mã lưu trữ để giải phóng mã cũ;
-- 3) soft-delete Supabase Auth user;
-- 4) giữ profile + registrations để không mất lịch sử.
--
-- Các policy dưới đây chặn JWT cũ của tài khoản đã bị xóa/khóa.
drop policy if exists profiles_select on public.profiles;

create policy profiles_select on public.profiles for
select
  to authenticated using (
    (
      id = auth.uid ()
      and active = true
    )
    or public.is_teacher ()
    or (
      public.current_app_role () = 'monitor'
      and class_name = public.current_app_class ()
    )
  );

drop policy if exists registrations_select on public.registrations;

create policy registrations_select on public.registrations for
select
  to authenticated using (
    (
      student_id = auth.uid ()
      and public.current_app_role () in ('student', 'monitor')
      and is_deleted = false
    )
    or (
      is_deleted = false
      and public.can_view_student (student_id)
    )
  );

drop policy if exists registrations_student_insert on public.registrations;

create policy registrations_student_insert on public.registrations for insert to authenticated
with
  check (
    public.current_app_role () in ('student', 'monitor')
    and student_id = auth.uid ()
    and (
      status in ('draft', 'submitted')
      or (
        status = 'approved'
        and approval_source = 'auto_rule'
        and public.smart_approval_is_enabled ()
        and exists (
          select
            1
          from
            public.smart_review_registration (content, note) s
          where
            s.auto_approve = true
        )
      )
    )
    and exists (
      select
        1
      from
        public.weeks w
      where
        w.id = week_id
        and w.status = 'open'
        and (
          public.registration_deadline_for_slot (week_id, weekday) is null
          or now() <= public.registration_deadline_for_slot (week_id, weekday)
        )
    )
  );

drop policy if exists registrations_student_update on public.registrations;

create policy registrations_student_update on public.registrations
for update
  to authenticated using (
    public.current_app_role () in ('student', 'monitor')
    and student_id = auth.uid ()
    and is_deleted = false
    and status in ('draft', 'submitted', 'needs_revision')
    and exists (
      select
        1
      from
        public.weeks w
      where
        w.id = week_id
        and w.status = 'open'
        and (
          public.registration_deadline_for_slot (week_id, weekday) is null
          or now() <= public.registration_deadline_for_slot (week_id, weekday)
          or registrations.status = 'needs_revision'
        )
    )
  )
with
  check (
    public.current_app_role () in ('student', 'monitor')
    and student_id = auth.uid ()
    and (
      status in ('draft', 'submitted')
      or (
        status = 'approved'
        and approval_source = 'auto_rule'
        and public.smart_approval_is_enabled ()
        and exists (
          select
            1
          from
            public.smart_review_registration (content, note) s
          where
            s.auto_approve = true
        )
      )
    )
  );

drop policy if exists audit_authenticated_insert on public.audit_logs;

create policy audit_authenticated_insert on public.audit_logs for insert to authenticated
with
  check (
    actor_id = auth.uid ()
    and public.current_app_role () is not null
  );

-- =========================
-- V7: Hybrid rule + OpenAI semantic review
-- =========================
-- SỔ TỰ HỌC V7 — HYBRID RULE + AI REVIEW
-- Chạy MỘT LẦN sau PATCH-V6.
--
-- Luồng:
-- 1. Rule rõ ràng học tập -> auto_rule.
-- 2. Rule giải trí/rủi ro rõ -> manual ngay.
-- 3. Trường hợp mơ hồ -> ai_review_status='pending'.
-- 4. Edge Function ai-review-registration gọi OpenAI.
-- 5. Chỉ AI đủ ngưỡng tin cậy mới approval_source='ai'; còn lại báo GV.
-- ===== CỘT AI =====
alter table public.registrations
add column if not exists ai_review_status text not null default 'not_needed',
add column if not exists ai_decision text,
add column if not exists ai_category text,
add column if not exists ai_confidence numeric,
add column if not exists ai_reason text,
add column if not exists ai_model text,
add column if not exists ai_reviewed_at timestamptz,
add column if not exists ai_review_count int not null default 0;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname='registrations_ai_review_status_check'
      and conrelid='public.registrations'::regclass
  ) then
    alter table public.registrations
      add constraint registrations_ai_review_status_check
      check (ai_review_status in ('not_needed','pending','processing','completed','error'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname='registrations_ai_decision_check'
      and conrelid='public.registrations'::regclass
  ) then
    alter table public.registrations
      add constraint registrations_ai_decision_check
      check (ai_decision is null or ai_decision in ('auto_approve','manual_review'));
  end if;
end $$;

do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname='registrations_approval_source_check'
      and conrelid='public.registrations'::regclass
  ) then
    alter table public.registrations
      drop constraint registrations_approval_source_check;
  end if;
end $$;

alter table public.registrations
add constraint registrations_approval_source_check check (approval_source in ('manual', 'auto_rule', 'ai'));

create index if not exists idx_registrations_ai_pending on public.registrations (ai_review_status, status);

-- ===== CÀI ĐẶT =====
insert into
  public.app_settings (key, value)
values
  ('ai_review_enabled', 'true'::jsonb),
  ('ai_auto_approve_threshold', '0.90'::jsonb)
on conflict (key) do nothing;

create or replace function public.ai_review_is_enabled () returns boolean language sql stable security definer
set
  search_path = public as $$
  select coalesce(
    (select value='true'::jsonb from public.app_settings where key='ai_review_enabled'),
    true
  )
$$;

create or replace function public.ai_auto_approve_threshold () returns numeric language sql stable security definer
set
  search_path = public as $$
  select greatest(
    0.50,
    least(
      0.99,
      coalesce(
        (select (value #>> '{}')::numeric from public.app_settings where key='ai_auto_approve_threshold'),
        0.90
      )
    )
  )
$$;

-- ===== RULE 3 NGẢ =====
-- route:
-- auto_rule = rõ ràng phù hợp -> tự duyệt ngay
-- manual    = có dấu hiệu giải trí/rủi ro -> GV duyệt, không cần AI
-- ai        = mơ hồ -> gửi AI đánh giá
create or replace function public.smart_review_route (p_content text, p_note text) returns table (route text, reason text) language plpgsql stable security definer
set
  search_path = public as $$
declare
  v_text text := lower(coalesce(p_content,'') || ' ' || coalesce(p_note,''));
  v_has_study boolean;
  v_has_device boolean;
  v_has_nonstudy boolean;
  v_is_specific_study boolean;
begin
  v_has_nonstudy :=
    v_text ~ '(chơi[[:space:]]*game|game[[:space:]]*giải[[:space:]]*trí|tiktok|facebook|instagram|xem[[:space:]]*phim|video[[:space:]]*giải[[:space:]]*trí|nghe[[:space:]]*nhạc|mạng[[:space:]]*xã[[:space:]]*hội|lướt[[:space:]]*mạng|chat|nhắn[[:space:]]*tin|giải[[:space:]]*trí|shopping|mua[[:space:]]*sắm)';

  v_has_device :=
    v_text ~ '(điện[[:space:]]*thoại|laptop|máy[[:space:]]*tính|tablet|ipad|chromebook|thiết[[:space:]]*bị[[:space:]]*điện[[:space:]]*tử|internet|website|youtube|ứng[[:space:]]*dụng|app)';

  v_has_study :=
    v_text ~ '(học|ôn|ôn[[:space:]]*tập|bài[[:space:]]*tập|làm[[:space:]]*bài|đọc[[:space:]]*sách|soạn[[:space:]]*bài|luyện|làm[[:space:]]*đề|nghiên[[:space:]]*cứu|tra[[:space:]]*cứu|tìm[[:space:]]*tài[[:space:]]*liệu|ghi[[:space:]]*chép|thuyết[[:space:]]*trình|dự[[:space:]]*án|lập[[:space:]]*trình|coding|programming|bài[[:space:]]*giảng|từ[[:space:]]*vựng|sgk|sách[[:space:]]*giáo[[:space:]]*khoa|kiểm[[:space:]]*tra|study|homework|research|practice|toán|ngữ[[:space:]]*văn|tiếng[[:space:]]*anh|vật[[:space:]]*lí|vật[[:space:]]*lý|hóa[[:space:]]*học|hoá[[:space:]]*học|sinh[[:space:]]*học|lịch[[:space:]]*sử|địa[[:space:]]*lí|địa[[:space:]]*lý|tin[[:space:]]*học)';

  -- Cụm học tập đủ cụ thể để rule tự duyệt không cần AI.
  v_is_specific_study :=
    v_text ~ '(ôn[[:space:]]*tập|làm[[:space:]]*bài|bài[[:space:]]*tập|làm[[:space:]]*đề|đọc[[:space:]]*(sgk|sách)|soạn[[:space:]]*bài|lập[[:space:]]*trình|bài[[:space:]]*giảng|tra[[:space:]]*cứu.*(toán|văn|anh|lý|lí|hóa|hoá|sinh|sử|địa|tin)|tìm[[:space:]]*tài[[:space:]]*liệu.*(học|môn|bài))';

  if v_has_nonstudy then
    return query select 'manual'::text, 'Có dấu hiệu giải trí/mạng xã hội; giữ lại để giáo viên duyệt.'::text;
    return;
  end if;

  if v_has_device and v_is_specific_study then
    return query select 'auto_rule'::text, 'Thiết bị điện tử đi kèm mục đích học tập rất rõ.'::text;
    return;
  end if;

  if not v_has_device and v_is_specific_study then
    return query select 'auto_rule'::text, 'Nội dung học tập đủ cụ thể để duyệt theo quy tắc.'::text;
    return;
  end if;

  -- Có tín hiệu học nhưng cách diễn đạt chưa đủ cụ thể, hoặc có thiết bị:
  -- để AI đọc ngữ nghĩa thay vì dựa hoàn toàn vào từ khóa.
  if v_has_study or v_has_device then
    return query select 'ai'::text, 'Nội dung có khả năng liên quan học tập nhưng cần AI đọc ngữ cảnh.'::text;
    return;
  end if;

  return query select 'ai'::text, 'Nội dung chưa rõ; chuyển AI phân loại ngữ nghĩa.'::text;
end;
$$;

-- ===== BEFORE TRIGGER =====
create or replace function public.apply_smart_approval () returns trigger language plpgsql security definer
set
  search_path = public as $$
declare
  v_enabled boolean := public.smart_approval_is_enabled();
  v_ai_enabled boolean := public.ai_review_is_enabled();
  v_route text;
  v_reason text;
  v_should_review boolean := false;
begin
  -- HS không được tự gán approved.
  if auth.uid() = new.student_id and new.status='approved' then
    new.status := 'submitted';
    new.approval_source := 'manual';
    new.approved_at := null;
    new.approved_by := null;
  end if;

  if new.status='submitted' then
    if tg_op='INSERT' then
      v_should_review := true;
    elsif old.status is distinct from 'submitted'
       or old.content is distinct from new.content
       or old.note is distinct from new.note then
      v_should_review := true;
    end if;
  end if;

  if v_should_review then
    -- Reset AI fields mỗi lần HS gửi lại nội dung.
    new.ai_decision := null;
    new.ai_category := null;
    new.ai_confidence := null;
    new.ai_reason := null;
    new.ai_model := null;
    new.ai_reviewed_at := null;

    if not v_enabled then
      new.status := 'submitted';
      new.approval_source := 'manual';
      new.auto_review_reason := 'Duyệt nhanh thông minh đang tắt.';
      new.ai_review_status := 'not_needed';
      new.approved_at := null;
      new.approved_by := null;
    else
      select r.route,r.reason into v_route,v_reason
      from public.smart_review_route(new.content,new.note) r;

      new.auto_review_reason := v_reason;

      if v_route='auto_rule' then
        new.status := 'approved';
        new.approval_source := 'auto_rule';
        new.ai_review_status := 'not_needed';
        new.approved_at := now();
        new.approved_by := null;

      elsif v_route='ai' and v_ai_enabled then
        new.status := 'submitted';
        new.approval_source := 'manual';
        new.ai_review_status := 'pending';
        new.approved_at := null;
        new.approved_by := null;

      else
        new.status := 'submitted';
        new.approval_source := 'manual';
        new.ai_review_status := 'not_needed';
        new.approved_at := null;
        new.approved_by := null;
      end if;
    end if;

  elsif new.status='approved' and auth.uid() is distinct from new.student_id then
    -- Giữ nguồn AI/rule nếu update đến từ backend; phê duyệt tay mới gắn manual.
    if new.approval_source not in ('auto_rule','ai') then
      new.approval_source := 'manual';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_apply_smart_approval on public.registrations;

create trigger trg_apply_smart_approval before insert
or
update of status,
content,
note on public.registrations for each row
execute function public.apply_smart_approval ();

-- ===== THÔNG BÁO GV =====
create or replace function public.sync_teacher_review_notification () returns trigger language plpgsql security definer
set
  search_path = public as $$
declare
  v_student_name text;
  v_reason text;
begin
  select full_name into v_student_name
  from public.profiles
  where id=new.student_id;

  v_reason := coalesce(new.ai_reason,new.auto_review_reason,'');

  -- Không báo GV khi AI vẫn đang xử lý.
  if new.status='submitted'
     and new.approval_source='manual'
     and new.ai_review_status not in ('pending','processing')
  then
    insert into public.teacher_notifications(
      registration_id,student_id,week_id,notification_type,title,message,is_read,created_at
    )
    values(
      new.id,new.student_id,new.week_id,'manual_review',
      case
        when new.ai_review_status='completed' then 'AI đề nghị giáo viên duyệt'
        when new.ai_review_status='error' then 'AI chưa xử lý được — cần giáo viên duyệt'
        else 'Đăng ký cần giáo viên duyệt'
      end,
      coalesce(v_student_name,'Học sinh') || ': ' ||
      left(coalesce(new.content,''),160) ||
      case when v_reason<>'' then ' — '||v_reason else '' end,
      false,now()
    )
    on conflict (registration_id,notification_type)
    do update set
      title=excluded.title,
      message=excluded.message,
      is_read=false,
      created_at=now();
  else
    update public.teacher_notifications
    set is_read=true
    where registration_id=new.id
      and notification_type='manual_review'
      and is_read=false;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_sync_teacher_review_notification on public.registrations;

create trigger trg_sync_teacher_review_notification
after insert
or
update of status,
content,
note,
approval_source,
ai_review_status,
ai_reason on public.registrations for each row
execute function public.sync_teacher_review_notification ();
-- V8.2.0 — Security hardening (safe to re-run)
-- Mục tiêu:
-- 1) bảo đảm class_members luôn dùng security_invoker
-- 2) chỉ cho authenticated đọc các cột an toàn
-- 3) không cho lộ email nội bộ từ view frontend

begin;

drop view if exists public.class_members;

create view public.class_members
with (security_invoker = on)
as
select id, student_code, full_name, role, class_name, active
from public.profiles
where
  id = auth.uid()
  or public.is_teacher()
  or (
    public.current_app_role() = 'monitor'
    and class_name = public.current_app_class()
  );

revoke all on public.class_members from anon;
revoke all on public.class_members from authenticated;
grant select on public.class_members to authenticated;

alter table public.profiles enable row level security;
revoke all on public.profiles from anon;
revoke select on public.profiles from authenticated;
grant select (id, student_code, full_name, role, class_name, active)
on public.profiles to authenticated;

commit;

-- Kiểm tra nhanh
select * from public.class_members limit 5;
-- V8.2.1 — server-only audit logs + rate limiting support
begin;

create table if not exists public.server_rate_limits (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete cascade,
  action text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_server_rate_limits_actor_action_time
  on public.server_rate_limits(actor_id, action, created_at desc);

revoke all on public.server_rate_limits from anon;
revoke all on public.server_rate_limits from authenticated;
alter table public.server_rate_limits enable row level security;

-- Audit log must be server-written only.
drop policy if exists audit_authenticated_insert on public.audit_logs;
revoke insert on public.audit_logs from authenticated;
revoke update on public.audit_logs from authenticated;
revoke delete on public.audit_logs from authenticated;

-- Teachers keep read access to audit logs.
drop policy if exists audit_teacher_select on public.audit_logs;
create policy audit_teacher_select
on public.audit_logs
for select
to authenticated
using (public.is_teacher());

commit;
-- V8.2.5 CUMULATIVE: bao gồm toàn bộ V8.2.4 + V8.2.5

-- ==========================================================
-- V8.2.4 — REGISTRATION SECURITY + AUTO WEEK OPEN
-- ==========================================================
-- Mục tiêu:
-- 1) HS có thể đăng ký lại một tiết sau khi bản cũ đã bị GV soft-delete.
-- 2) Tuần hiện tại + tuần kế tiếp tự động mở theo ngày, không phụ thuộc mở thủ công.
-- 3) Hạn mặc định: 20:00 tối hôm trước từng buổi.
-- 4) needs_revision vẫn sửa được sau deadline/tuần đã qua.

begin;

-- ===== Deadline mặc định =====
alter table public.weeks
  alter column deadline_mode set default 'per_session_20';

update public.weeks
set deadline_mode='per_session_20',
    registration_deadline=null
where deadline_mode is null
   or deadline_mode='week_before_20';

-- ===== Cho phép đăng ký mới sau soft-delete mà vẫn giữ lịch sử cũ =====
-- Constraint UNIQUE cũ chặn một slot mới dù hàng cũ đã is_deleted=true.
alter table public.registrations
  drop constraint if exists registrations_student_id_week_id_weekday_period_number_key;

drop index if exists public.registrations_student_id_week_id_weekday_period_number_key;

create unique index if not exists uq_registrations_active_student_slot
on public.registrations(student_id,week_id,weekday,period_number)
where is_deleted=false;

-- ===== Trạng thái mở được tính tự động =====
create or replace function public.week_registration_is_open(p_week_id uuid)
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  with target as (
    select id,school_year_id,week_number,start_date,status
    from public.weeks
    where id=p_week_id
  ),
  clock as (
    select (now() at time zone 'Asia/Ho_Chi_Minh')::date as today
  ),
  anchor as (
    select w.week_number
    from public.weeks w
    join target t on t.school_year_id=w.school_year_id
    cross join clock c
    where c.today between w.start_date and (w.start_date + 6)
    order by w.week_number
    limit 1
  )
  select coalesce(
    t.status <> 'holiday'
    and a.week_number is not null
    and t.week_number between a.week_number and (a.week_number + 1),
    false
  )
  from target t
  left join anchor a on true
$$;

revoke all on function public.week_registration_is_open(uuid) from public;
grant execute on function public.week_registration_is_open(uuid) to authenticated;

-- Đồng bộ trạng thái lưu trong bảng tại thời điểm chạy patch để Dashboard dễ đọc.
with clock as (
  select (now() at time zone 'Asia/Ho_Chi_Minh')::date as today
),
anchors as (
  select distinct on (w.school_year_id)
    w.school_year_id,
    w.week_number
  from public.weeks w
  cross join clock c
  where c.today between w.start_date and (w.start_date + 6)
  order by w.school_year_id,w.week_number
)
update public.weeks w
set status=case
  when w.status='holiday' then 'holiday'::public.week_status
  when a.week_number is not null
       and w.week_number between a.week_number and a.week_number+1
    then 'open'::public.week_status
  when w.end_date < (select today from clock)
    then 'locked'::public.week_status
  else 'upcoming'::public.week_status
end
from anchors a
where a.school_year_id=w.school_year_id
  and w.status<>'holiday';

-- ===== RLS đăng ký =====
drop policy if exists registrations_student_insert on public.registrations;
create policy registrations_student_insert
on public.registrations
for insert
to authenticated
with check (
  public.current_app_role() in ('student','monitor')
  and student_id=auth.uid()
  and is_deleted=false
  and (
    status in ('draft','submitted')
    or (
      status='approved'
      and approval_source='auto_rule'
      and public.smart_approval_is_enabled()
      and exists (
        select 1
        from public.smart_review_registration(content,note) s
        where s.auto_approve=true
      )
    )
  )
  and public.week_registration_is_open(week_id)
  and (
    public.registration_deadline_for_slot(week_id,weekday) is null
    or now() <= public.registration_deadline_for_slot(week_id,weekday)
  )
);

drop policy if exists registrations_student_update on public.registrations;
create policy registrations_student_update
on public.registrations
for update
to authenticated
using (
  public.current_app_role() in ('student','monitor')
  and student_id=auth.uid()
  and is_deleted=false
  and status in ('draft','submitted','needs_revision')
  and (
    registrations.status='needs_revision'
    or (
      public.week_registration_is_open(week_id)
      and (
        public.registration_deadline_for_slot(week_id,weekday) is null
        or now() <= public.registration_deadline_for_slot(week_id,weekday)
      )
    )
  )
)
with check (
  public.current_app_role() in ('student','monitor')
  and student_id=auth.uid()
  and is_deleted=false
  and (
    status in ('draft','submitted')
    or (
      status='approved'
      and approval_source='auto_rule'
      and public.smart_approval_is_enabled()
      and exists (
        select 1
        from public.smart_review_registration(content,note) s
        where s.auto_approve=true
      )
    )
  )
);

commit;

-- ==========================================================
-- V8.2.5 — NEXT ACTION WEEK + RE-REVIEW + EMERGENCY REGISTER
-- ==========================================================
begin;

alter table public.registrations
  add column if not exists is_emergency boolean not null default false,
  add column if not exists emergency_reason text,
  add column if not exists emergency_requested_at timestamptz;

create index if not exists idx_registrations_emergency
on public.registrations(is_emergency, emergency_requested_at desc)
where is_emergency=true;

-- Thời điểm bắt đầu thực tế của một tiết.
create or replace function public.study_session_start(
  p_week_id uuid,
  p_weekday int,
  p_period_number int
)
returns timestamptz
language sql
stable
security definer
set search_path=public
as $$
  select (
    (
      w.start_date + (greatest(1,least(5,p_weekday))-1)
    )::timestamp + p.start_time
  ) at time zone 'Asia/Ho_Chi_Minh'
  from public.weeks w
  join public.periods p on p.period_number=p_period_number
  where w.id=p_week_id
$$;

revoke all on function public.study_session_start(uuid,int,int) from public;
grant execute on function public.study_session_start(uuid,int,int) to authenticated;

-- Dùng trong RLS để bảo đảm client không tự gắn/cởi cờ "khẩn cấp".
create or replace function public.registration_emergency_flag_matches(
  p_registration_id uuid,
  p_flag boolean
)
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select coalesce(
    (select r.is_emergency=p_flag
     from public.registrations r
     where r.id=p_registration_id),
    false
  )
$$;

revoke all on function public.registration_emergency_flag_matches(uuid,boolean) from public;
grant execute on function public.registration_emergency_flag_matches(uuid,boolean) to authenticated;

-- Insert thường: không được tự giả danh đăng ký khẩn cấp.
drop policy if exists registrations_student_insert on public.registrations;
create policy registrations_student_insert
on public.registrations
for insert
to authenticated
with check (
  public.current_app_role() in ('student','monitor')
  and student_id=auth.uid()
  and is_deleted=false
  and is_emergency=false
  and (
    status in ('draft','submitted')
    or (
      status='approved'
      and approval_source='auto_rule'
      and public.smart_approval_is_enabled()
      and exists (
        select 1
        from public.smart_review_registration(content,note) s
        where s.auto_approve=true
      )
    )
  )
  and public.week_registration_is_open(week_id)
  and (
    public.registration_deadline_for_slot(week_id,weekday) is null
    or now() <= public.registration_deadline_for_slot(week_id,weekday)
  )
);

-- Cho HS sửa cả bản đã approved, nhưng chỉ trước deadline.
-- Khi gửi lại, frontend đổi về submitted và trigger sẽ duyệt lại từ đầu.
-- needs_revision vẫn được sửa sau deadline theo cơ chế cũ.
drop policy if exists registrations_student_update on public.registrations;
create policy registrations_student_update
on public.registrations
for update
to authenticated
using (
  public.current_app_role() in ('student','monitor')
  and student_id=auth.uid()
  and is_deleted=false
  and status in ('draft','submitted','needs_revision','approved')
  and (
    status='needs_revision'
    or (
      public.week_registration_is_open(week_id)
      and (
        public.registration_deadline_for_slot(week_id,weekday) is null
        or now() <= public.registration_deadline_for_slot(week_id,weekday)
      )
      and now() < public.study_session_start(week_id,weekday,period_number)
    )
  )
)
with check (
  public.current_app_role() in ('student','monitor')
  and student_id=auth.uid()
  and is_deleted=false
  and public.registration_emergency_flag_matches(id,is_emergency)
  and (
    status in ('draft','submitted')
    or (
      status='approved'
      and approval_source='auto_rule'
      and public.smart_approval_is_enabled()
      and exists (
        select 1
        from public.smart_review_registration(content,note) s
        where s.auto_approve=true
      )
    )
  )
);

-- Emergency luôn chuyển GV duyệt, không auto-rule/AI.
create or replace function public.apply_smart_approval()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_enabled boolean := public.smart_approval_is_enabled();
  v_ai_enabled boolean := public.ai_review_is_enabled();
  v_route text;
  v_reason text;
  v_should_review boolean := false;
begin
  if auth.uid()=new.student_id and new.status='approved' then
    new.status:='submitted';
    new.approval_source:='manual';
    new.approved_at:=null;
    new.approved_by:=null;
  end if;

  if new.status='submitted' then
    if tg_op='INSERT' then
      v_should_review:=true;
    elsif old.status is distinct from 'submitted'
       or old.content is distinct from new.content
       or old.note is distinct from new.note then
      v_should_review:=true;
    end if;
  end if;

  if v_should_review then
    new.ai_decision:=null;
    new.ai_category:=null;
    new.ai_confidence:=null;
    new.ai_reason:=null;
    new.ai_model:=null;
    new.ai_reviewed_at:=null;

    if coalesce(new.is_emergency,false) then
      new.status:='submitted';
      new.approval_source:='manual';
      new.auto_review_reason:='Đăng ký bổ sung khẩn cấp sau deadline; giáo viên cần duyệt.';
      new.ai_review_status:='not_needed';
      new.approved_at:=null;
      new.approved_by:=null;

    elsif not v_enabled then
      new.status:='submitted';
      new.approval_source:='manual';
      new.auto_review_reason:='Duyệt nhanh thông minh đang tắt.';
      new.ai_review_status:='not_needed';
      new.approved_at:=null;
      new.approved_by:=null;

    else
      select r.route,r.reason into v_route,v_reason
      from public.smart_review_route(new.content,new.note) r;

      new.auto_review_reason:=v_reason;

      if v_route='auto_rule' then
        new.status:='approved';
        new.approval_source:='auto_rule';
        new.ai_review_status:='not_needed';
        new.approved_at:=now();
        new.approved_by:=null;

      elsif v_route='ai' and v_ai_enabled then
        new.status:='submitted';
        new.approval_source:='manual';
        new.ai_review_status:='pending';
        new.approved_at:=null;
        new.approved_by:=null;

      else
        new.status:='submitted';
        new.approval_source:='manual';
        new.ai_review_status:='not_needed';
        new.approved_at:=null;
        new.approved_by:=null;
      end if;
    end if;

  elsif new.status='approved' and auth.uid() is distinct from new.student_id then
    if new.approval_source not in ('auto_rule','ai') then
      new.approval_source:='manual';
    end if;
  end if;

  return new;
end;
$$;

-- Notification rõ riêng trường hợp khẩn cấp.
create or replace function public.sync_teacher_review_notification()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_student_name text;
  v_reason text;
begin
  select full_name into v_student_name
  from public.profiles
  where id=new.student_id;

  v_reason:=coalesce(new.ai_reason,new.auto_review_reason,'');

  if new.status='submitted'
     and new.approval_source='manual'
     and new.ai_review_status not in ('pending','processing')
  then
    insert into public.teacher_notifications(
      registration_id,student_id,week_id,notification_type,title,message,is_read,created_at
    )
    values(
      new.id,new.student_id,new.week_id,'manual_review',
      case
        when coalesce(new.is_emergency,false) then '🚨 Đăng ký bổ sung khẩn cấp'
        when new.ai_review_status='completed' then 'AI đề nghị giáo viên duyệt'
        when new.ai_review_status='error' then 'AI chưa xử lý được — cần giáo viên duyệt'
        else 'Đăng ký cần giáo viên duyệt'
      end,
      coalesce(v_student_name,'Học sinh') || ': ' ||
      left(coalesce(new.content,''),160) ||
      case
        when coalesce(new.is_emergency,false) and coalesce(new.emergency_reason,'')<>''
          then ' — Lý do bổ sung: '||left(new.emergency_reason,180)
        when v_reason<>'' then ' — '||v_reason
        else ''
      end,
      false,now()
    )
    on conflict (registration_id,notification_type)
    do update set
      title=excluded.title,
      message=excluded.message,
      is_read=false,
      created_at=now();
  else
    update public.teacher_notifications
    set is_read=true
    where registration_id=new.id
      and notification_type='manual_review'
      and is_read=false;
  end if;

  return new;
end;
$$;

commit;
-- SỔ TỰ HỌC V8.3.0
-- BẢN VÁ CỘNG DỒN CHO CƠ SỞ DỮ LIỆU ĐÃ Ở V8.2.5.
--
-- AN TOÀN DỮ LIỆU:
-- - Không xóa bảng, tài khoản hay đăng ký.
-- - Bổ sung cờ thiết bị với mặc định false cho dữ liệu cũ.
-- - Chuẩn hóa policy cuối cùng để không có nhiều policy cùng mở rộng quyền.
--
-- Trước khi chạy: sao lưu Supabase.
-- Sau khi chạy: chạy VERIFY-V830.sql.

begin;

alter table public.registrations
  add column if not exists uses_electronic_device boolean not null default false;

comment on column public.registrations.uses_electronic_device is
  'Học sinh khai báo có sử dụng thiết bị điện tử trong buổi tự học hay không.';

create index if not exists idx_registrations_week_slot_active
  on public.registrations (week_id, weekday, period_number, status)
  where is_deleted = false;

create index if not exists idx_registrations_student_week_active
  on public.registrations (student_id, week_id)
  where is_deleted = false;

-- Một policy SELECT duy nhất:
-- chủ bản ghi đọc đăng ký của mình; cán sự/GV chỉ đọc bản đã gửi mà họ được phép xem.
drop policy if exists registrations_select_v830 on public.registrations;
drop policy if exists registrations_select on public.registrations;

create policy registrations_select
on public.registrations
for select
to authenticated
using (
  is_deleted = false
  and (
    (
      student_id = (select auth.uid())
      and public.current_app_role() in ('student','monitor')
    )
    or (
      status <> 'draft'
      and public.can_view_student(student_id)
    )
  )
);

-- Đăng ký thường: học sinh/cán sự chỉ tạo cho chính mình, không giả cờ khẩn cấp.
drop policy if exists registrations_student_insert_v830 on public.registrations;
drop policy if exists registrations_student_insert on public.registrations;

create policy registrations_student_insert
on public.registrations
for insert
to authenticated
with check (
  public.current_app_role() in ('student','monitor')
  and student_id = (select auth.uid())
  and is_deleted = false
  and is_emergency = false
  and (
    status in ('draft','submitted')
    or (
      status = 'approved'
      and approval_source = 'auto_rule'
      and public.smart_approval_is_enabled()
      and exists (
        select 1
        from public.smart_review_registration(content,note) s
        where s.auto_approve = true
      )
    )
  )
  and public.week_registration_is_open(week_id)
  and (
    public.registration_deadline_for_slot(week_id,weekday) is null
    or now() <= public.registration_deadline_for_slot(week_id,weekday)
  )
);

-- Sửa đăng ký: giữ nguyên luật V8.2.5, gồm sửa bản approved trước hạn và
-- sửa needs_revision sau hạn. Cờ khẩn cấp không được đổi từ trình duyệt.
drop policy if exists registrations_student_update_v830 on public.registrations;
drop policy if exists registrations_student_update on public.registrations;

create policy registrations_student_update
on public.registrations
for update
to authenticated
using (
  public.current_app_role() in ('student','monitor')
  and student_id = (select auth.uid())
  and is_deleted = false
  and status in ('draft','submitted','needs_revision','approved')
  and (
    status = 'needs_revision'
    or (
      public.week_registration_is_open(week_id)
      and (
        public.registration_deadline_for_slot(week_id,weekday) is null
        or now() <= public.registration_deadline_for_slot(week_id,weekday)
      )
      and now() < public.study_session_start(week_id,weekday,period_number)
    )
  )
)
with check (
  public.current_app_role() in ('student','monitor')
  and student_id = (select auth.uid())
  and is_deleted = false
  and public.registration_emergency_flag_matches(id,is_emergency)
  and (
    status in ('draft','submitted')
    or (
      status = 'approved'
      and approval_source = 'auto_rule'
      and public.smart_approval_is_enabled()
      and exists (
        select 1
        from public.smart_review_registration(content,note) s
        where s.auto_approve = true
      )
    )
  )
);

-- Giáo viên giữ quyền quản lý; cán sự không thỏa is_teacher().
drop policy if exists registrations_teacher_update_v830 on public.registrations;
drop policy if exists registrations_teacher_update on public.registrations;

create policy registrations_teacher_update
on public.registrations
for update
to authenticated
using (public.is_teacher())
with check (public.is_teacher());

revoke all on table public.registrations from anon;
grant select, insert, update on table public.registrations to authenticated;


-- V8.3.0 least-privilege execution matrix for SECURITY DEFINER helpers.
-- Reset inherited/default grants first, then restore only policy/server call paths.
revoke execute on function public.ai_auto_approve_threshold() from public, anon, authenticated, service_role;
revoke execute on function public.ai_review_is_enabled() from public, anon, authenticated, service_role;
revoke execute on function public.apply_smart_approval() from public, anon, authenticated, service_role;
revoke execute on function public.can_view_class() from public, anon, authenticated, service_role;
revoke execute on function public.can_view_student(uuid) from public, anon, authenticated, service_role;
revoke execute on function public.current_app_class() from public, anon, authenticated, service_role;
revoke execute on function public.current_app_role() from public, anon, authenticated, service_role;
revoke execute on function public.handle_new_user() from public, anon, authenticated, service_role;
revoke execute on function public.is_teacher() from public, anon, authenticated, service_role;
revoke execute on function public.registration_deadline_for_slot(uuid,integer) from public, anon, authenticated, service_role;
revoke execute on function public.registration_emergency_flag_matches(uuid,boolean) from public, anon, authenticated, service_role;
revoke execute on function public.smart_approval_is_enabled() from public, anon, authenticated, service_role;
revoke execute on function public.smart_review_registration(text,text) from public, anon, authenticated, service_role;
revoke execute on function public.smart_review_route(text,text) from public, anon, authenticated, service_role;
revoke execute on function public.study_session_start(uuid,integer,integer) from public, anon, authenticated, service_role;
revoke execute on function public.sync_teacher_review_notification() from public, anon, authenticated, service_role;
revoke execute on function public.week_registration_is_open(uuid) from public, anon, authenticated, service_role;

grant execute on function public.current_app_role() to authenticated;
grant execute on function public.is_teacher() to authenticated;
grant execute on function public.can_view_student(uuid) to authenticated;
grant execute on function public.registration_deadline_for_slot(uuid,integer) to authenticated;
grant execute on function public.registration_emergency_flag_matches(uuid,boolean) to authenticated;
grant execute on function public.smart_approval_is_enabled() to authenticated;
grant execute on function public.smart_review_registration(text,text) to authenticated;
grant execute on function public.study_session_start(uuid,integer,integer) to authenticated;
grant execute on function public.week_registration_is_open(uuid) to authenticated;

grant execute on function public.registration_deadline_for_slot(uuid,integer) to service_role;
grant execute on function public.study_session_start(uuid,integer,integer) to service_role;

commit;

notify pgrst, 'reload schema';
