<script setup lang="ts">
import { KeyRound, LockKeyhole, Pencil, RotateCcw, Trash2 } from 'lucide-vue-next'
import AppButton from '../ui/AppButton.vue'
import RemoteUserAvatar from '../profile/RemoteUserAvatar.vue'
import type { AdminClassRecord, AdminTeacherRecord } from '../../features/admin/admin-directory'
withDefaults(defineProps<{teacher:AdminTeacherRecord;classes:AdminClassRecord[];busy?:boolean}>(),{busy:false})
const emit=defineEmits<{edit:[];toggle:[];reset:[];hardDelete:[]}>()
</script>
<template>
  <article class="teacher-card" :class="{inactive:!teacher.active,busy}"><header><RemoteUserAvatar :user-id="teacher.id" :name="teacher.fullName" :code="teacher.code" size="md"/><div><h3>{{ teacher.fullName || 'Giáo viên' }}</h3><small>{{ teacher.code }}</small></div><span class="state">{{ teacher.active?'Hoạt động':'Đã khóa' }}</span></header><div class="classes"><span v-for="item in classes" :key="item.id">{{ item.code }}</span><small v-if="!classes.length">Chưa được phân lớp</small></div><footer><AppButton variant="secondary" :disabled="busy" @click="emit('edit')"><Pencil/>Sửa</AppButton><AppButton :variant="teacher.active?'secondary':'success'" :loading="busy" @click="emit('toggle')"><LockKeyhole v-if="teacher.active"/><RotateCcw v-else/>{{ teacher.active?'Khóa':'Mở khóa' }}</AppButton><AppButton variant="secondary" :disabled="busy" @click="emit('reset')"><KeyRound/>Mật khẩu</AppButton><AppButton variant="danger" :disabled="busy||classes.length>0" :title="classes.length?'Hãy gỡ tất cả phân công lớp trước khi xóa vĩnh viễn.':'Xóa vĩnh viễn giáo viên'" @click="emit('hardDelete')"><Trash2/>Xóa vĩnh viễn</AppButton></footer></article>
</template>
<style scoped>
.teacher-card{display:grid;gap:12px;border:1px solid var(--border);border-radius:16px;background:linear-gradient(145deg,var(--surface-raised),color-mix(in srgb,var(--wash-mint) 48%,var(--surface)));padding:15px}.teacher-card.inactive{opacity:.75}.teacher-card.busy{border-color:color-mix(in srgb,var(--color-primary) 28%,var(--border));box-shadow:0 0 0 3px color-mix(in srgb,var(--color-primary) 8%,transparent)}.teacher-card header{display:grid;grid-template-columns:44px minmax(0,1fr) auto;gap:10px;align-items:center}.teacher-card h3{margin:0;font-size:1rem}.teacher-card small{color:var(--text-muted)}.state{font-size:var(--font-size-ui-min);font-weight:900;color:var(--color-success)}.classes{display:flex;gap:6px;flex-wrap:wrap}.classes span{padding:4px 8px;border-radius:999px;background:var(--surface-soft);font-size:var(--font-size-ui-min);color:var(--text-muted)}footer{display:flex;gap:7px;flex-wrap:wrap}footer :deep(.app-button){min-height:39px;padding:7px 10px;font-size:var(--font-size-ui-min)}footer :deep(svg){width:14px}@media(max-width:480px){.teacher-card header{grid-template-columns:44px minmax(0,1fr)}.state{grid-column:2}.teacher-card footer :deep(.app-button){width:100%}}
</style>
