<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Copy, Eye, EyeOff, KeyRound, Shuffle } from 'lucide-vue-next'
import AppButton from '../ui/AppButton.vue'
const props=withDefaults(defineProps<{open:boolean;name?:string;code?:string;saving?:boolean;error?:string}>(),{name:'',code:'',saving:false,error:''})
const emit=defineEmits<{close:[];save:[password:string]}>()
const password=ref(''),confirmPassword=ref(''),show=ref(false),copied=ref(false)
watch(()=>props.open,value=>{if(value){password.value='';confirmPassword.value='';show.value=false;copied.value=false}})
const invalid=computed(()=>Boolean(password.value)&&(password.value.length<8||!/[A-Za-zÀ-ỹ]/.test(password.value)||!/\d/.test(password.value)))
const mismatch=computed(()=>Boolean(confirmPassword.value)&&password.value!==confirmPassword.value)
function randomPassword(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';const bytes=new Uint32Array(12);crypto.getRandomValues(bytes);password.value=[...bytes].map(value=>alphabet[value%alphabet.length]).join('')+'7a';confirmPassword.value=password.value;show.value=true}
async function copyPassword(){if(!password.value)return;await navigator.clipboard?.writeText(password.value);copied.value=true;setTimeout(()=>copied.value=false,1500)}
function submit(){if(invalid.value||mismatch.value||password.value.length<8)return;emit('save',password.value)}
</script>
<template>
  <div v-if="open" class="backdrop" @click.self="emit('close')" @keydown.esc="emit('close')"><section class="dialog" role="dialog" aria-modal="true"><header><span><KeyRound/></span><div><small>BẢO MẬT TÀI KHOẢN</small><h2>Đặt lại mật khẩu</h2></div></header><div class="target"><b>{{ name||code }}</b><small>{{ code }}</small></div><div v-if="error" class="error">{{ error }}</div><form @submit.prevent="submit"><label>Mật khẩu mới<div class="password-input"><input v-model="password" :type="show?'text':'password'" autocomplete="new-password" minlength="8"><button type="button" :aria-label="show?'Ẩn mật khẩu':'Hiện mật khẩu'" @click="show=!show"><EyeOff v-if="show"/><Eye v-else/></button></div><small :class="{danger:invalid}">Ít nhất 8 ký tự, có chữ và số.</small></label><label>Xác nhận mật khẩu<input v-model="confirmPassword" :type="show?'text':'password'" autocomplete="new-password"><small v-if="mismatch" class="danger">Hai mật khẩu chưa khớp.</small></label><div class="helpers"><AppButton variant="secondary" @click="randomPassword"><Shuffle/>Tạo mật khẩu ngẫu nhiên</AppButton><AppButton variant="secondary" :disabled="!password" @click="copyPassword"><Copy/>{{ copied?'Đã sao chép':'Sao chép' }}</AppButton></div><p class="security-note">Mật khẩu mới không được ghi vào Nhật ký hệ thống và sẽ không hiển thị lại sau khi đóng hộp thoại.</p><div class="actions"><AppButton variant="secondary" :disabled="saving" @click="emit('close')">Hủy</AppButton><AppButton type="submit" :loading="saving" :disabled="invalid||mismatch||password.length<8">Đặt lại mật khẩu</AppButton></div></form></section></div>
</template>
<style scoped>
.backdrop{position:fixed;inset:0;z-index:125;background:var(--overlay);display:grid;place-items:center;padding:18px}.dialog{width:min(520px,100%);border:1px solid var(--border);border-radius:24px;background:var(--surface-raised);padding:22px;box-shadow:var(--shadow-md)}header{display:flex;align-items:center;gap:12px}header>span{width:44px;height:44px;display:grid;place-items:center;border-radius:14px;background:var(--wash-violet);color:var(--color-primary)}header svg{width:22px}header small{color:var(--color-primary);font-size:var(--font-size-ui-min);font-weight:900;letter-spacing:.08em}h2{margin:2px 0}.target{display:grid;gap:2px;margin:14px 0;padding:11px 13px;border-radius:13px;background:var(--surface-soft)}.target small{color:var(--text-muted)}form{display:grid;gap:12px}label{display:grid;gap:6px;font-weight:800}input{width:100%;min-height:46px;border:1px solid var(--border);border-radius:12px;background:var(--input);color:var(--text);padding:9px 11px}.password-input{display:grid;grid-template-columns:1fr auto;border:1px solid var(--border);border-radius:12px;background:var(--input);overflow:hidden}.password-input input{border:0;border-radius:0}.password-input button{width:46px;border:0;background:transparent;color:var(--text-muted)}.password-input svg{width:19px}label small{color:var(--text-muted);font-weight:500}.danger{color:var(--color-danger)!important}.helpers{display:flex;gap:8px;flex-wrap:wrap}.security-note{margin:0;padding:10px 12px;border-radius:12px;background:var(--wash-mint);color:var(--text-muted);font-size:var(--font-size-ui-min);line-height:1.5}.actions{display:flex;justify-content:flex-end;gap:8px}.error{padding:9px 11px;border-radius:11px;background:color-mix(in srgb,var(--color-danger) 8%,var(--surface));color:var(--color-danger);font-weight:750}@media(max-width:520px){.backdrop{align-items:end;padding:8px}.helpers,.actions{display:grid;grid-template-columns:1fr}.helpers :deep(.app-button),.actions :deep(.app-button){width:100%}}
</style>
