<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import { CalendarRange, Link2 } from 'lucide-vue-next'
import AppButton from '../ui/AppButton.vue'
import type { AdminClassRecord, AdminTimetableAssignmentRecord, AdminTimetableTemplateRecord, AdminTimetableVersionRecord } from '../../features/admin/admin-directory'
const props=defineProps<{schoolYearId:string;yearStart:string;yearEnd:string;classes:AdminClassRecord[];templates:AdminTimetableTemplateRecord[];versions:AdminTimetableVersionRecord[];assignments:AdminTimetableAssignmentRecord[];busy?:boolean}>()
const emit=defineEmits<{assign:[payload:{classId:string;schoolYearId:string;templateVersionId:string;effectiveFrom:string;effectiveTo:string}]}>()
const form=reactive({classId:'',templateId:'',versionId:'',from:props.yearStart,to:props.yearEnd})
watch(()=>[props.yearStart,props.yearEnd],()=>{if(!form.from)form.from=props.yearStart;if(!form.to)form.to=props.yearEnd})
const versionOptions=computed(()=>props.versions.filter(row=>row.templateId===form.templateId).sort((a,b)=>b.version-a.version))
const latestVersionId=computed(()=>versionOptions.value[0]?.id??'')
watch([()=>form.templateId,latestVersionId],()=>{
  if(!form.templateId){form.versionId='';return}
  if(!versionOptions.value.some(row=>row.id===form.versionId))form.versionId=latestVersionId.value
},{immediate:true})
const selectedTemplate=computed(()=>props.templates.find(row=>row.id===form.templateId)??null)
const selectedVersion=computed(()=>versionOptions.value.find(row=>row.id===form.versionId)??null)
const selectedClassAssignments=computed(()=>props.assignments.filter(row=>row.classId===form.classId&&row.active).sort((a,b)=>a.effectiveFrom.localeCompare(b.effectiveFrom)))
const canSave=computed(()=>Boolean(form.classId&&form.versionId&&form.from&&form.to&&form.from<=form.to&&form.from>=props.yearStart&&form.to<=props.yearEnd&&!props.busy))
function timeRange(start:string|null,end:string|null){return start&&end?`${start}–${end}`:'Không cấu hình'}
function templateName(versionId:string){const version=props.versions.find(row=>row.id===versionId);return props.templates.find(row=>row.id===version?.templateId)?.name??'Mẫu TKB'}
function submit(){if(!canSave.value)return;emit('assign',{classId:form.classId,schoolYearId:props.schoolYearId,templateVersionId:form.versionId,effectiveFrom:form.from,effectiveTo:form.to})}
</script>
<template><section class="assignment"><div class="assignment-head"><div><b><CalendarRange/>Gán mẫu TKB cho lớp</b><span>Có hiệu lực theo khoảng ngày; khi gán khoảng mới, lịch sử ngoài khoảng đó được giữ lại.</span></div></div><div class="assignment-form"><label>Lớp<select v-model="form.classId"><option value="">Chọn lớp</option><option v-for="item in classes" :key="item.id" :value="item.id">{{ item.code }}</option></select></label><label>Mẫu<select v-model="form.templateId"><option value="">Chọn mẫu</option><option v-for="item in templates" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label>Phiên bản<select v-model="form.versionId" :disabled="!versionOptions.length"><option v-for="item in versionOptions" :key="item.id" :value="item.id">v{{ item.version }}</option></select></label><label>Từ ngày<input v-model="form.from" type="date" :min="yearStart" :max="yearEnd"></label><label>Đến ngày<input v-model="form.to" type="date" :min="yearStart" :max="yearEnd"></label><AppButton :disabled="!canSave" :loading="busy" @click="submit"><Link2/>Gán TKB</AppButton></div><div v-if="selectedVersion" class="selected-template-summary"><div class="summary-title"><b>{{ selectedTemplate?.name ?? 'Mẫu TKB' }} · v{{ selectedVersion.version }}</b><span>Thông tin phiên bản đang chọn</span></div><div class="template-facts"><span><b>Buổi sáng</b>{{ timeRange(selectedVersion.config.morningStart,selectedVersion.config.morningEnd) }}</span><span><b>Buổi chiều</b>{{ timeRange(selectedVersion.config.afternoonStart,selectedVersion.config.afternoonEnd) }}</span><span><b>Thời lượng tiết</b>{{ selectedVersion.config.defaultPeriodMinutes }} phút</span></div></div><div v-else-if="form.templateId" class="empty selected-template-empty">Mẫu TKB này chưa có phiên bản đã lưu. Hãy tạo hoặc lưu một phiên bản trước khi gán cho lớp.</div><div v-if="form.classId" class="history"><b>Lịch hiệu lực hiện tại</b><div v-if="!selectedClassAssignments.length" class="empty">Chưa có mẫu được gán.</div><div v-for="row in selectedClassAssignments" :key="row.id" class="history-row"><span>{{ row.effectiveFrom }} → {{ row.effectiveTo }}</span><strong>{{ templateName(row.templateVersionId) }}</strong></div></div></section></template>
<style scoped>.assignment{display:grid;gap:10px;padding-top:14px;border-top:1px solid color-mix(in srgb,var(--color-primary) 10%,var(--border))}.assignment-head>div{display:grid;gap:3px}.assignment-head b{display:flex;gap:7px;align-items:center}.assignment-head svg,.assignment :deep(svg){width:16px}.assignment-head span,.empty{font-size:var(--font-size-ui-min);color:var(--text-muted)}.assignment-form{display:grid;grid-template-columns:1fr 1.2fr .7fr 1fr 1fr auto;gap:8px;align-items:end}label{display:grid;gap:4px;font-size:var(--font-size-ui-min);font-weight:800;color:var(--text-muted)}select,input{min-height:40px;border:1px solid var(--border);border-radius:10px;padding:7px 9px;background:var(--input);color:var(--text)}select:disabled{opacity:.6}.selected-template-summary{display:grid;grid-template-columns:minmax(180px,.8fr) minmax(0,2fr);gap:12px;align-items:center;padding:11px 12px;border:1px solid color-mix(in srgb,var(--color-primary) 16%,var(--border));border-radius:13px;background:color-mix(in srgb,var(--color-primary) 4%,var(--surface))}.summary-title{display:grid;gap:3px}.summary-title b{font-size:.84rem}.summary-title span{font-size:var(--font-size-ui-min);color:var(--text-muted)}.template-facts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.template-facts span{display:grid;gap:2px;padding:7px 9px;border-radius:9px;background:var(--surface);font-size:var(--font-size-ui-min);color:var(--text-muted)}.template-facts b{font-size:var(--font-size-ui-min);color:var(--text)}.selected-template-empty{padding:10px 12px;border-radius:11px;background:var(--surface-soft)}.history{display:grid;gap:6px;padding:10px;border-radius:13px;background:var(--surface-soft)}.history-row{display:flex;justify-content:space-between;gap:12px;padding:7px 9px;border-radius:9px;background:var(--surface);font-size:var(--font-size-ui-min)}.history-row span{color:var(--text-muted)}@media(max-width:1100px){.assignment-form{grid-template-columns:repeat(3,1fr)}.selected-template-summary{grid-template-columns:1fr}}@media(max-width:650px){.assignment-form,.template-facts{grid-template-columns:1fr}.history-row{display:grid}}</style>
