<script setup lang="ts">
import RemoteUserAvatar from '../profile/RemoteUserAvatar.vue'
import type { AdminAssignmentRecord, AdminClassRecord, AdminTeacherRecord } from '../../features/admin/admin-directory'
const props=defineProps<{classes:AdminClassRecord[];teachers:AdminTeacherRecord[];assignments:AdminAssignmentRecord[];busyKey:string|null}>()
const emit=defineEmits<{change:[payload:{classId:string;teacherId:string;enabled:boolean}]}>()
const assigned=(classId:string,teacherId:string)=>props.assignments.some(row=>row.classId===classId&&row.teacherId===teacherId&&row.active)
</script>
<template>
  <div class="matrix-wrap"><table class="matrix"><thead><tr><th>Giáo viên</th><th v-for="item in classes" :key="item.id">{{ item.code }}</th></tr></thead><tbody><tr v-for="teacher in teachers" :key="teacher.id"><th><span class="who"><RemoteUserAvatar :user-id="teacher.id" :name="teacher.fullName" :code="teacher.code" size="sm"/><span><b>{{ teacher.fullName || teacher.code }}</b><small>{{ teacher.code }}</small></span></span></th><td v-for="item in classes" :key="item.id"><label class="permission"><input type="checkbox" :checked="assigned(item.id,teacher.id)" :disabled="!teacher.active||busyKey===`${item.id}:${teacher.id}`" :aria-label="`${teacher.fullName} phụ trách ${item.code}`" @change="emit('change',{classId:item.id,teacherId:teacher.id,enabled:($event.target as HTMLInputElement).checked})"><span aria-hidden="true"></span></label></td></tr></tbody></table><div class="permission-mobile"><article v-for="teacher in teachers" :key="teacher.id"><header><RemoteUserAvatar :user-id="teacher.id" :name="teacher.fullName" :code="teacher.code" size="sm"/><span><b>{{ teacher.fullName || teacher.code }}</b><small>{{ teacher.code }}</small></span></header><div><label v-for="item in classes" :key="item.id"><input type="checkbox" :checked="assigned(item.id,teacher.id)" :disabled="!teacher.active||busyKey===`${item.id}:${teacher.id}`" @change="emit('change',{classId:item.id,teacherId:teacher.id,enabled:($event.target as HTMLInputElement).checked})"><span>{{ item.code }}</span></label></div></article></div></div>
</template>
<style scoped>
.matrix-wrap{overflow:auto}.matrix{width:100%;border-collapse:collapse}.matrix th,.matrix td{padding:10px;border-bottom:1px solid var(--border);text-align:center}.matrix thead th{font-size:var(--font-size-ui-min);color:var(--text-muted)}.matrix tbody th{text-align:left;min-width:214px}.matrix tbody th small{display:block;color:var(--text-muted);font-weight:500}
/* Avatar giúp Admin nhận ra đúng người khi nhiều GV trùng họ hoặc tên gần giống nhau. */
.who{display:flex;align-items:center;gap:10px;min-width:0}.who>span{display:grid;min-width:0}.who b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.permission{display:inline-grid;place-items:center}.permission input{width:20px;height:20px;accent-color:var(--color-primary)}.permission-mobile{display:none}@media(max-width:760px){.matrix{display:none}.permission-mobile{display:grid;gap:9px}.permission-mobile article{border:1px solid var(--border);border-radius:13px;padding:11px}.permission-mobile header{display:flex;align-items:center;gap:10px;min-width:0}.permission-mobile header>span{display:grid;min-width:0}.permission-mobile header small{display:block;color:var(--text-muted)}.permission-mobile article>div{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.permission-mobile label{display:flex;align-items:center;gap:5px;border-radius:999px;padding:6px 9px;background:var(--surface-soft);font-size:var(--font-size-ui-min)}}
</style>
