<script setup lang="ts">
import { computed, ref } from 'vue'
import { onClickOutside } from '@vueuse/core'
import { ChevronDown, LogOut, Menu, Moon, SlidersHorizontal, Sun } from 'lucide-vue-next'
import IconButton from '../ui/IconButton.vue'
import { useAuthStore } from '../../stores/auth'
import { useContextStore } from '../../stores/context'
import { usePreferencesStore } from '../../stores/preferences'
import { getWeekLifecycle } from '../../features/weeks/week-lifecycle'
import { dirtyRegistry } from '../../features/shared/dirty-registry'
import type { UserRole } from '../../types/legacy'

const emit=defineEmits<{menu:[];logout:[]}>()
const auth=useAuthStore();const context=useContextStore();const preferences=usePreferencesStore()
const profileOpen=ref(false);const profileMenu=ref<HTMLElement|null>(null)
onClickOutside(profileMenu,()=>{profileOpen.value=false})
const state=computed(()=>auth.legacyState)
const isAdmin=computed(()=>auth.currentUser?.role==='admin')
const isTeacher=computed(()=>auth.currentUser?.role==='teacher')
const operationalWeekId=computed(()=>state.value?getWeekLifecycle({weeks:state.value.weeks,periods:state.value.periods,getSlots:()=>state.value?.schedule??[]}).currentWeekId:null)
const roleLabels:Record<UserRole,string>={student:'Học sinh',monitor:'Cán sự lớp',teacher:'Giáo viên',admin:'Quản trị viên'}
const roleLabel=computed(()=>auth.currentUser?roleLabels[auth.currentUser.role]:'')
const profileRoleLine=computed(()=>{const user=auth.currentUser;if(!user)return'';const classCode=context.selectedClass?.code||String(state.value?.settings.className??'');return user.role==='student'||user.role==='monitor'?`${roleLabel.value}${classCode?` · ${classCode}`:''}`:roleLabel.value})
const initials=computed(()=>String(auth.currentUser?.name||auth.currentUser?.code||'?').trim().split(/\s+/).slice(-2).map(part=>part[0]||'').join('').toUpperCase()||'?')
function confirmContextChange(){if(!dirtyRegistry.hasDirty())return true;if(!window.confirm('Thay đổi chưa được lưu sẽ bị bỏ. Tiếp tục?'))return false;dirtyRegistry.discardAll();return true}
async function changeClass(event:Event){const select=event.target as HTMLSelectElement;const id=select.value;if(!confirmContextChange()){select.value=context.selectedClassId??'';return}context.selectClass(id);await auth.reload(id,context.selectedSchoolYearId);context.hydrate(auth.legacyState)}
async function changeSchoolYear(event:Event){const select=event.target as HTMLSelectElement;const id=select.value;if(!confirmContextChange()){select.value=context.selectedSchoolYearId??'';return}context.selectSchoolYear(id);await auth.reload(null,id);context.hydrate(auth.legacyState)}
function changeWeek(event:Event){const select=event.target as HTMLSelectElement;const id=select.value;if(!confirmContextChange()){select.value=context.selectedWeekId??'';return}context.selectWeek(id,{manual:id!==operationalWeekId.value})}
function requestLogout(){profileOpen.value=false;emit('logout')}
</script>
<template>
  <header class="topbar">
    <div class="left">
      <IconButton label="Mở menu" class="mobile-menu" @click="emit('menu')"><Menu/></IconButton>
      <label v-if="isTeacher||isAdmin" class="school-year-bubble"><span>Năm học</span><i v-if="context.selectedSchoolYear?.active" class="year-status-dot" aria-label="Năm học đang hoạt động"></i><select :value="context.selectedSchoolYearId??''" @change="changeSchoolYear"><option v-for="item in context.schoolYears" :key="item.id" :value="item.id">{{ item.name }}</option></select></label>
      <div v-else class="school-year-bubble static-year"><span>Năm học</span><b>{{ context.selectedSchoolYear?.name||state?.settings.schoolYear||'—' }}</b></div>
    </div>
    <div class="context-controls">
      <label v-if="isTeacher" class="compact control-bubble"><span>Lớp</span><select :value="context.selectedClassId??''" @change="changeClass"><option v-for="item in context.classes" :key="item.id" :value="item.id">{{ item.code }}{{ item.name&&item.name!==item.code?` · ${item.name}`:'' }}</option></select></label>
      <label v-if="!isAdmin" class="compact control-bubble"><span>Tuần</span><select :value="context.selectedWeekId??''" @change="changeWeek"><option v-for="item in context.weeks" :key="item.id" :value="item.id">Tuần {{ item.number }}</option></select></label>
      <IconButton class="theme-bubble" label="Đổi giao diện" @click="preferences.toggleTheme"><Sun v-if="preferences.resolvedTheme==='dark'"/><Moon v-else/></IconButton>
      <div v-if="auth.currentUser" ref="profileMenu" class="profile-menu">
        <button class="profile-chip" type="button" :title="`${auth.currentUser.name} · ${roleLabel}`" :aria-expanded="profileOpen" aria-haspopup="menu" @click="profileOpen=!profileOpen">
          <span class="profile-avatar">{{ initials }}</span><span class="profile-copy"><b>{{ auth.currentUser.name }}</b><small>{{ profileRoleLine }}</small></span><ChevronDown class="profile-chevron" :class="{open:profileOpen}"/>
        </button>
        <div v-if="profileOpen" class="profile-dropdown" role="menu">
          <div class="profile-summary"><span class="profile-avatar large">{{ initials }}</span><div><b>{{ auth.currentUser.name }}</b><small>{{ roleLabel }} · {{ auth.currentUser.code }}</small></div></div>
          <div v-if="!isAdmin" class="profile-class"><span>{{ context.selectedClass?.name||context.selectedClass?.code||state?.settings.className||'Lớp học' }}</span><small>{{ state?.settings.schoolYear||'' }}</small></div>
          <RouterLink v-if="auth.currentUser.role==='student'||auth.currentUser.role==='monitor'" class="profile-settings" to="/settings" role="menuitem" @click="profileOpen=false"><SlidersHorizontal/>Tùy chọn cá nhân</RouterLink>
          <button type="button" class="profile-logout" role="menuitem" @click="requestLogout"><LogOut/>Đăng xuất</button>
        </div>
      </div>
    </div>
  </header>
</template>
<style scoped>
.topbar{position:sticky;top:0;z-index:20;min-height:78px;display:flex;align-items:center;justify-content:space-between;gap:14px;padding:12px 18px;background:transparent;transition:background var(--theme-transition),color var(--theme-transition)}
.left{display:flex;gap:10px;align-items:center}.school-year-bubble,.control-bubble,.theme-bubble{border-radius:999px;background:color-mix(in srgb,var(--surface) 82%,transparent);box-shadow:0 8px 24px rgb(79 55 73 / .07);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);transition:transform var(--transition-fast),box-shadow var(--transition-fast),background var(--theme-transition),border-color var(--theme-transition),color var(--theme-transition)}.school-year-bubble{display:flex;align-items:center;gap:8px;min-height:46px;min-width:166px;padding:5px 8px 5px 13px;border:1px solid color-mix(in srgb,var(--color-coral) 14%,var(--border));color:var(--text-muted);font-size:.78rem;font-weight:850}.school-year-bubble>span{white-space:nowrap;color:var(--color-coral)}.year-status-dot{width:7px;height:7px;flex:0 0 7px;border-radius:999px;background:var(--color-success);box-shadow:0 0 0 3px color-mix(in srgb,var(--color-success) 13%,transparent)}.school-year-bubble select{min-width:105px;height:34px;border:0;border-radius:999px;background:color-mix(in srgb,var(--wash-peach) 68%,var(--surface));color:var(--text);padding:0 28px 0 10px;font-size:.95rem;font-weight:850;outline:0}.school-year-bubble.static-year{display:grid;align-content:center;gap:0}.school-year-bubble.static-year b{color:var(--text);font-size:.92rem}.school-year-bubble:hover{transform:translateY(-2px);box-shadow:0 12px 30px color-mix(in srgb,var(--color-coral) 10%,transparent);background:color-mix(in srgb,var(--surface) 88%,var(--wash-peach))}
.context-controls{display:flex;align-items:center;gap:9px}.compact{display:flex;align-items:center;gap:7px;color:var(--text-muted);font-size:.86rem;font-weight:800}.control-bubble{min-height:44px;padding:4px 7px 4px 12px;border:1px solid color-mix(in srgb,var(--color-primary) 11%,var(--border))}.compact span{color:var(--color-primary)}.compact select{height:34px;min-width:98px;border:0;border-radius:999px;background:color-mix(in srgb,var(--wash-peach) 58%,transparent);color:var(--text);padding:0 28px 0 10px;font-size:.95rem;font-weight:800;outline:0;transition:background var(--transition-fast),box-shadow var(--transition-fast),transform var(--transition-fast),color var(--theme-transition)}.control-bubble:hover{transform:translateY(-2px);box-shadow:0 12px 28px color-mix(in srgb,var(--color-primary) 11%,transparent);background:color-mix(in srgb,var(--surface) 88%,var(--wash-cream))}.compact select:hover{background:color-mix(in srgb,var(--wash-peach) 78%,var(--surface))}.compact select:focus{box-shadow:0 0 0 3px color-mix(in srgb,var(--color-primary) 11%,transparent);background:color-mix(in srgb,var(--wash-violet) 64%,var(--surface))}
.theme-bubble{width:44px!important;height:44px!important;border-color:color-mix(in srgb,var(--color-sun) 18%,var(--border))!important;background:color-mix(in srgb,var(--surface) 84%,var(--wash-cream))!important;box-shadow:0 8px 24px rgb(79 55 73 / .07)!important}.theme-bubble:hover{border-color:color-mix(in srgb,var(--color-sun) 44%,var(--border))!important;background:color-mix(in srgb,var(--wash-cream) 82%,var(--surface))!important}
.profile-menu{position:relative}.profile-chip{display:flex;align-items:center;gap:9px;min-height:46px;padding:5px 10px 5px 6px;border:1px solid color-mix(in srgb,var(--color-primary) 12%,var(--border));border-radius:999px;background:color-mix(in srgb,var(--surface) 84%,transparent);color:var(--text);box-shadow:0 8px 24px rgb(79 55 73 / .07);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);transition:transform var(--transition-fast),box-shadow var(--transition-fast),border-color var(--transition-fast),background var(--theme-transition);cursor:pointer}.profile-chip:hover{transform:translateY(-2px) scale(1.01);box-shadow:0 12px 30px color-mix(in srgb,var(--color-coral) 10%,transparent);border-color:color-mix(in srgb,var(--color-coral) 26%,var(--border));background:color-mix(in srgb,var(--surface) 88%,var(--wash-peach))}.profile-avatar{width:35px;height:35px;display:grid;place-items:center;border-radius:999px;background:linear-gradient(135deg,var(--wash-peach),var(--wash-violet));color:var(--color-primary);font-weight:900;transition:transform var(--transition-fast),box-shadow var(--transition-fast)}.profile-chip:hover .profile-avatar{transform:rotate(-2deg) scale(1.06);box-shadow:0 5px 12px color-mix(in srgb,var(--color-primary) 16%,transparent)}.profile-avatar.large{width:44px;height:44px}.profile-copy{display:grid;line-height:1.15;min-width:0;text-align:left}.profile-copy b{max-width:150px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:.84rem}.profile-copy small,.profile-summary small,.profile-class small{margin-top:3px;color:var(--text-muted);font-size:.7rem;font-weight:750}.profile-chevron{width:15px;height:15px;color:var(--text-muted);transition:transform var(--transition-fast)}.profile-chevron.open{transform:rotate(180deg)}
.profile-dropdown{position:absolute;right:0;top:calc(100% + 10px);width:min(292px,calc(100vw - 24px));padding:12px;border:1px solid color-mix(in srgb,var(--color-coral) 11%,var(--border));border-radius:22px;background:color-mix(in srgb,var(--surface-raised) 94%,transparent);box-shadow:0 22px 54px rgb(79 55 73 / .17);backdrop-filter:blur(22px);-webkit-backdrop-filter:blur(22px);display:grid;gap:9px;transform-origin:top right}.profile-summary{display:flex;align-items:center;gap:11px;padding:7px 6px}.profile-summary>div,.profile-class{display:grid;min-width:0}.profile-summary b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.profile-class{padding:10px 12px;border-radius:15px;background:linear-gradient(135deg,color-mix(in srgb,var(--wash-peach) 86%,var(--surface)),color-mix(in srgb,var(--wash-violet) 58%,var(--surface)));font-size:.8rem;font-weight:800}.profile-settings,.profile-logout{display:flex;align-items:center;gap:9px;min-height:42px;padding:9px 12px;border:0;border-radius:13px;background:transparent;font-weight:850;cursor:pointer;transition:transform var(--transition-fast),background var(--transition-fast),box-shadow var(--transition-fast),color var(--transition-fast)}.profile-settings{color:var(--color-primary)}.profile-settings:hover{background:var(--wash-violet);transform:translateX(3px);box-shadow:0 7px 18px color-mix(in srgb,var(--color-primary) 9%,transparent)}.profile-settings svg,.profile-logout svg{width:18px;transition:transform var(--transition-fast)}.profile-settings:hover svg{transform:rotate(-8deg) scale(1.08)}.profile-logout{color:var(--color-danger)}.profile-logout:hover{background:var(--wash-coral);transform:translateX(3px);box-shadow:0 7px 18px color-mix(in srgb,var(--color-danger) 8%,transparent)}.profile-logout:hover svg{transform:translateX(2px)}.mobile-menu{display:none}
@media(max-width:980px){.profile-copy{display:none}.profile-chip{padding:5px}.profile-chevron{display:none}.identity-bubble{min-width:118px}}
@media(max-width:760px){.mobile-menu{display:grid}.identity-bubble{display:none}.compact span{display:none}.compact{font-size:.82rem}.control-bubble{padding:3px 5px}.compact select{max-width:112px;min-width:82px;height:34px;font-size:.86rem;padding-left:9px}.topbar{min-height:66px;padding:9px 10px}.context-controls{gap:6px}.theme-bubble{width:40px!important;height:40px!important}.profile-chip{min-height:40px}}
@media(max-width:430px){.compact select{max-width:98px}.profile-dropdown{position:fixed;right:10px;top:66px}}
</style>
