<script setup lang="ts">
import { computed } from 'vue'
import { AlertCircle, CheckCircle2, ClipboardCheck, Laptop2, TriangleAlert, UserCheck, UsersRound } from 'lucide-vue-next'
import AppCard from '../components/ui/AppCard.vue'
import AppBadge from '../components/ui/AppBadge.vue'
import { useAuthStore } from '../stores/auth'
import { useContextStore } from '../stores/context'
import { useWeekData } from '../features/weeks/queries'
import { buildDashboardMetrics } from '../features/dashboard/dashboard-model'
import { useDailyQuote } from '../features/owl/daily-quote'
import { useNowTicker } from '../features/shared/useNowTicker'
import { needsTeacherAction } from '../features/registrations/registration-model'
const dashboardIllustrationUrl = `${import.meta.env.BASE_URL}assets/images/teacher-dashboard-illustration.png`
const auth=useAuthStore();const context=useContextStore();const nowMs=useNowTicker(30_000);const classId=computed(()=>context.selectedClassId);const weekId=computed(()=>context.selectedWeekId);const weekQuery=useWeekData(classId,weekId)
const isStudent=computed(()=>auth.currentUser?.role==='student')
const isMonitor=computed(()=>auth.currentUser?.role==='monitor')
const isLearner=computed(()=>isStudent.value||isMonitor.value)
const slots=computed(()=>{const state=auth.legacyState;if(!state)return[];const overrides=(weekQuery.data.value?.overrides??state.overrides??[]).filter(row=>row.weekId===weekId.value);return overrides.length?overrides.filter(row=>row.active!==false).map(row=>({dow:row.dow,period:row.period})):state.schedule??[]})
const registrations=computed(()=>weekQuery.data.value?.registrations??auth.legacyState?.registrations.filter(row=>row.weekId===weekId.value)??[])
const personalRegistrations=computed(()=>registrations.value.filter(row=>row.studentId===auth.currentUser?.id))
const week=computed(()=>context.selectedWeek)
const classMetrics=computed(()=>buildDashboardMetrics({users:auth.legacyState?.users??[],registrations:registrations.value,slots:slots.value,week:week.value,periods:auth.legacyState?.periods??[],nowMs:nowMs.value}))
const personalMetrics=computed(()=>buildDashboardMetrics({users:auth.currentUser?[auth.currentUser]:[],registrations:personalRegistrations.value,slots:slots.value,week:week.value,periods:auth.legacyState?.periods??[],nowMs:nowMs.value}))
const managerQueue=computed(()=>registrations.value.filter(row=>needsTeacherAction(row)).length)
const dailyQuoteQuery=useDailyQuote();const dailyQuote=computed(()=>dailyQuoteQuery.data.value)
const isFetching=computed(()=>weekQuery.isFetching.value)
</script>
<template><div class="page-stack dashboard-page">
  <section class="welcome app-card"><div><span class="week-kicker">TỔNG QUAN TUẦN</span><h1 class="week-title">TUẦN {{ week?.number??'–' }}</h1><div class="week-dates" v-if="week">{{ week.startDate }} → {{ week.endDate }}</div><h2 class="welcome-name">Chào {{ auth.currentUser?.name||'bạn' }}</h2><p v-if="isStudent">Theo dõi đăng ký, phản hồi và những việc bạn cần hoàn thành trong tuần.</p><p v-else-if="isMonitor">Theo dõi việc học của bạn và hỗ trợ lớp hoàn thành đăng ký đúng hạn.</p><p v-else>{{ auth.legacyState?.settings.announcement||'Theo dõi tiến độ tự học và các mục cần xử lý của lớp.' }}</p></div><img :src="dashboardIllustrationUrl" alt=""/></section>

  <template v-if="isStudent">
    <section class="role-section"><div class="role-heading"><span>CÁ NHÂN CỦA TÔI</span><h2>Việc cần theo dõi</h2></div><div class="metrics learner-metrics"><AppCard><ClipboardCheck/><b>{{ personalMetrics.submitted }}/{{ personalMetrics.slots }}</b><span>Đăng ký tuần này</span></AppCard><AppCard><CheckCircle2/><b>{{ personalMetrics.approved }}</b><span>Đã duyệt</span></AppCard><AppCard><AlertCircle/><b>{{ personalMetrics.needsRevision }}</b><span>Cần chỉnh sửa</span></AppCard><AppCard><TriangleAlert/><b>{{ personalMetrics.issues }}</b><span>Báo cáo lỗi</span></AppCard></div></section>
  </template>

  <template v-else-if="isMonitor">
    <section class="role-section"><div class="role-heading"><span>CÁ NHÂN CỦA TÔI</span><h2>Tiến độ của tôi</h2></div><div class="metrics learner-metrics"><AppCard><ClipboardCheck/><b>{{ personalMetrics.submitted }}/{{ personalMetrics.slots }}</b><span>Đăng ký tuần này</span></AppCard><AppCard><CheckCircle2/><b>{{ personalMetrics.approved }}</b><span>Đã duyệt</span></AppCard><AppCard><AlertCircle/><b>{{ personalMetrics.needsRevision }}</b><span>Cần chỉnh sửa</span></AppCard><AppCard><TriangleAlert/><b>{{ personalMetrics.issues }}</b><span>Báo cáo lỗi</span></AppCard></div></section>
    <section class="role-section"><div class="role-heading"><span>HỖ TRỢ LỚP</span><h2>Tình hình lớp</h2></div><div class="metrics class-support"><AppCard><UsersRound/><b>{{ classMetrics.students }}</b><span>Học sinh</span></AppCard><AppCard><UserCheck/><b>{{ classMetrics.completion }}%</b><span>Đã đăng ký</span></AppCard><AppCard><AlertCircle/><b>{{ classMetrics.needsRevision }}</b><span>Cần chỉnh sửa</span></AppCard><AppCard><TriangleAlert/><b>{{ classMetrics.issues }}</b><span>Báo cáo lỗi</span></AppCard></div></section>
  </template>

  <section v-else class="metrics manager-metrics"><AppCard><UsersRound/><b>{{ classMetrics.students }}</b><span>Học sinh</span></AppCard><AppCard><CheckCircle2/><b>{{ classMetrics.completion }}%</b><span>Đã đăng ký</span></AppCard><AppCard><ClipboardCheck/><b>{{ managerQueue }}</b><span>Cần GV xử lý</span></AppCard><AppCard><TriangleAlert/><b>{{ classMetrics.issues }}</b><span>Báo cáo lỗi</span></AppCard><AppCard><Laptop2/><b>{{ classMetrics.electronicDevices }}</b><span>Có thiết bị</span></AppCard></section>

  <section class="daily-quote"><AppCard padding="lg"><span class="quote-kicker">Danh ngôn hôm nay</span><blockquote>“{{ dailyQuote?.text || 'Mỗi ngày học một điều mới là một bước tiến.' }}”</blockquote><cite>— {{ dailyQuote?.author || 'Cú Thông Thái' }}</cite></AppCard></section>
  <section class="grid"><AppCard padding="lg"><div class="page-header"><div><h2>Tiến độ tuần</h2><p>{{ isLearner?'Tính trên các buổi tự học của bạn trong tuần đang xem.':'Dữ liệu của lớp được tải theo đúng tuần đang chọn.' }}</p></div><AppBadge :tone="isFetching?'info':'success'">{{ isFetching?'Đang đồng bộ':'Đã đồng bộ' }}</AppBadge></div><div class="progress"><span :style="{width:`${(isLearner?personalMetrics:classMetrics).completion}%`}"></span></div><div class="summary"><span>{{ (isLearner?personalMetrics:classMetrics).submitted }}/{{ (isLearner?personalMetrics:classMetrics).expected }} lượt đăng ký</span><span>{{ (isLearner?personalMetrics:classMetrics).approved }} đã duyệt</span></div></AppCard><AppCard padding="lg"><h2>Cần chú ý</h2><p class="muted" v-if="(isLearner?personalMetrics:classMetrics).needsRevision===0&&(isLearner?personalMetrics:classMetrics).issues===0&&!(!isLearner&&managerQueue)">Hiện chưa có đăng ký cần chú ý trong tuần đang xem.</p><p v-if="(isLearner?personalMetrics:classMetrics).needsRevision"><b>{{ (isLearner?personalMetrics:classMetrics).needsRevision }}</b> đăng ký đang cần học sinh chỉnh sửa.</p><p v-if="!isLearner&&managerQueue"><b>{{ managerQueue }}</b> đăng ký đang cần giáo viên xử lý.</p><p v-if="(isLearner?personalMetrics:classMetrics).issues"><b>{{ (isLearner?personalMetrics:classMetrics).issues }}</b> đăng ký đã chuyển sang Báo cáo lỗi.</p><RouterLink v-if="(isLearner?personalMetrics:classMetrics).issues" class="issue-link interactive-link" to="/issues">Xem Báo cáo lỗi →</RouterLink></AppCard></section>
</div></template>
<style scoped>
.dashboard-page{max-width:1500px;margin:0 auto}.week-kicker,.role-heading span{display:inline-block;color:var(--color-primary);font-size:.76rem;font-weight:900;letter-spacing:.12em}.week-title{margin:6px 0 4px;font-size:clamp(2.8rem,6vw,5.2rem);line-height:.98;font-weight:950;letter-spacing:-.045em;background:linear-gradient(105deg,var(--color-primary),var(--color-info),var(--color-sky));-webkit-background-clip:text;background-clip:text;color:transparent}.week-dates{display:inline-flex;margin:5px 0 15px;padding:6px 10px;border-radius:10px;background:color-mix(in srgb,var(--surface) 78%,transparent);border:1px solid color-mix(in srgb,var(--color-primary) 12%,var(--border));color:var(--text-muted);font-size:.82rem;font-weight:800}.welcome-name{margin:0 0 5px;font-size:clamp(1.2rem,2.4vw,1.75rem)}
.welcome{display:grid;grid-template-columns:minmax(0,1fr) minmax(240px,390px);align-items:center;padding:30px;overflow:hidden;position:relative;background:radial-gradient(circle at 12% 18%,color-mix(in srgb,var(--wash-pink) 88%,transparent),transparent 34%),radial-gradient(circle at 82% 18%,color-mix(in srgb,var(--wash-sky) 86%,transparent),transparent 32%),linear-gradient(135deg,color-mix(in srgb,var(--wash-violet) 92%,transparent),color-mix(in srgb,var(--wash-mint) 72%,transparent))}.welcome::after{content:"";position:absolute;right:-34px;bottom:-54px;width:190px;height:190px;border-radius:50%;background:color-mix(in srgb,var(--color-sun) 10%,transparent);pointer-events:none}.welcome>div,.welcome img{position:relative;z-index:1}.welcome p{color:var(--text-muted);max-width:58ch}.welcome img{justify-self:end;max-height:230px}.role-section{display:grid;gap:10px}.role-heading h2{margin:3px 0 0;font-size:1.25rem}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px}.learner-metrics,.class-support{grid-template-columns:repeat(4,minmax(0,1fr))}.metrics :deep(.card){--metric-accent:var(--color-primary);--metric-wash:var(--wash-violet);display:grid;grid-template-columns:auto 1fr;column-gap:12px;align-items:center;background:linear-gradient(145deg,color-mix(in srgb,var(--surface) 96%,transparent),color-mix(in srgb,var(--metric-wash) 88%,transparent));border-color:color-mix(in srgb,var(--metric-accent) 22%,var(--border))}.metrics :deep(.card:nth-child(1)){--metric-accent:var(--color-sky);--metric-wash:var(--wash-sky)}.metrics :deep(.card:nth-child(2)){--metric-accent:var(--color-mint);--metric-wash:var(--wash-mint)}.metrics :deep(.card:nth-child(3)){--metric-accent:var(--color-coral);--metric-wash:var(--wash-coral)}.metrics :deep(.card:nth-child(4)){--metric-accent:var(--color-sun);--metric-wash:var(--wash-sun)}.metrics :deep(.card:nth-child(5)){--metric-accent:var(--color-lilac);--metric-wash:var(--wash-violet)}.metrics :deep(svg){grid-row:1/3;width:28px;color:var(--metric-accent)}.metrics b{font-size:1.62rem;color:var(--text)}.metrics span{color:var(--text-muted);font-size:.82rem;font-weight:750}
.daily-quote :deep(.card){position:relative;overflow:hidden;background:linear-gradient(120deg,color-mix(in srgb,var(--wash-sky) 92%,transparent),color-mix(in srgb,var(--wash-violet) 90%,transparent) 46%,color-mix(in srgb,var(--wash-pink) 90%,transparent));border-color:color-mix(in srgb,var(--color-lilac) 20%,var(--border))}.daily-quote :deep(.card)::before{content:"✦";position:absolute;right:24px;top:12px;color:var(--color-sun);font-size:2rem;opacity:.65}.quote-kicker{color:var(--color-primary);font-size:.76rem;font-weight:900;letter-spacing:.08em}.daily-quote blockquote{margin:10px 0 6px;font-size:clamp(1rem,2vw,1.2rem);line-height:1.6;font-weight:800}.daily-quote cite{color:var(--text-muted);font-style:normal}
.grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:18px}.grid h2{margin:0}.progress{height:13px;background:var(--surface-soft);border-radius:999px;overflow:hidden;margin:26px 0 10px}.progress span{display:block;height:100%;background:var(--gradient-celebrate);border-radius:inherit;transition:width .4s ease}.summary{display:flex;justify-content:space-between;gap:12px;color:var(--text-muted);font-size:.86rem;font-weight:700}.issue-link{display:inline-flex;margin-top:8px;color:var(--color-warning);font-weight:850;text-decoration:none}
@media(max-width:1100px){.metrics,.learner-metrics,.class-support{grid-template-columns:repeat(2,1fr)}}@media(max-width:900px){.grid{grid-template-columns:1fr}.welcome{grid-template-columns:1fr}.welcome img{max-height:180px;justify-self:center}}@media(max-width:480px){.metrics,.learner-metrics,.class-support{grid-template-columns:1fr}.welcome{padding:20px}}
</style>
