<script setup lang="ts">
import { computed, ref } from 'vue'
import { GraduationCap, Plus, Search, UserCheck, UserRoundX, UsersRound } from 'lucide-vue-next'
import { useQueryClient } from '@tanstack/vue-query'
import AppButton from '../components/ui/AppButton.vue'
import AppCard from '../components/ui/AppCard.vue'
import InlineStatus, { type InlineStatusState } from '../components/ui/InlineStatus.vue'
import StudentDirectory from '../components/students/StudentDirectory.vue'
import StudentAccountDialog from '../components/students/StudentAccountDialog.vue'
import { createStudentAccount, resetStudentPassword, restoreStudent, softDeleteStudent, updateStudentAccount, useStudentDirectory, type StudentMutationRuntime } from '../features/students/student-directory'
import { useAuthStore } from '../stores/auth'
import { useContextStore } from '../stores/context'
import type { DirectoryUser, UserRole } from '../types/legacy'

const auth=useAuthStore(),context=useContextStore(),queryClient=useQueryClient(),classId=computed(()=>context.selectedClassId)
const directory=useStudentDirectory(classId)
const query=ref(''),role=ref<'all'|'student'|'monitor'>('all'),stateFilter=ref<'active'|'deleted'|'all'>('active'),dialogOpen=ref(false),editing=ref<DirectoryUser|null>(null),saving=ref(false),error=ref(''),busyId=ref<string|null>(null),status=ref<InlineStatusState>('idle'),statusMessage=ref('')
const users=computed(()=>directory.data.value??[])
const visible=computed(()=>{const q=query.value.trim().toLocaleLowerCase('vi');return users.value.filter(user=>(!q||`${user.code} ${user.fullName}`.toLocaleLowerCase('vi').includes(q))&&(role.value==='all'||user.role===role.value)&&(stateFilter.value==='all'||(stateFilter.value==='active'?user.active:!user.active)))})
const counts=computed(()=>({student:users.value.filter(u=>u.role==='student').length,monitor:users.value.filter(u=>u.role==='monitor').length,active:users.value.filter(u=>u.active).length,deleted:users.value.filter(u=>!u.active).length}))
const classes=computed(()=>auth.legacyState?.availableClasses.map(item=>({id:item.id,code:item.code,name:item.name}))??[])
function runtime():StudentMutationRuntime{if(!classId.value)throw new Error('Chưa chọn lớp.');return{classId:classId.value,queryClient,reload:async()=>{await auth.reload(classId.value,context.selectedSchoolYearId);context.hydrate(auth.legacyState)}}}
function notify(state:InlineStatusState,message:string){status.value=state;statusMessage.value=message}
function openCreate(){editing.value=null;error.value='';dialogOpen.value=true}
function openEdit(user:DirectoryUser){editing.value=user;error.value='';dialogOpen.value=true}
async function save(value:{changeCode:boolean;code:string;fullName:string;role:UserRole;classId:string|null;active:boolean;password:string}){saving.value=true;error.value='';try{if(editing.value)await updateStudentAccount(runtime(),editing.value.id,value);else{const result=await createStudentAccount(runtime(),value);const password=String(result.password??'');notify('success',password?`Đã tạo ${value.code}. Mật khẩu tạm: ${password}`:`Đã tạo ${value.code}.`)}dialogOpen.value=false;if(editing.value)notify('success',`Đã cập nhật ${value.code}.`)}catch(e){error.value=e instanceof Error?e.message:'Không lưu được tài khoản.'}finally{saving.value=false}}
async function copy(user:DirectoryUser){try{if(!navigator.clipboard?.writeText)throw new Error('Trình duyệt không hỗ trợ Clipboard API.');await navigator.clipboard.writeText(user.code);notify('success',`Đã sao chép mã ${user.code}.`)}catch(e){notify('error',e instanceof Error?e.message:'Không sao chép được mã đăng nhập.')}}
async function reset(user:DirectoryUser){const p1=window.prompt(`Mật khẩu tạm mới cho ${user.code} (ít nhất 8 ký tự, có chữ và số):`)??'';if(!p1)return;if(p1.length<8||!/\p{L}/u.test(p1)||!/[0-9]/.test(p1)){notify('error','Mật khẩu cần ít nhất 8 ký tự và có cả chữ lẫn số.');return}busyId.value=user.id;try{await resetStudentPassword(user.id,p1);notify('success',`Đã đặt lại mật khẩu cho ${user.code}.`)}catch(e){notify('error',e instanceof Error?e.message:'Không đặt lại được mật khẩu.')}finally{busyId.value=null}}
async function remove(user:DirectoryUser){const confirmCode=window.prompt(`Xóa mềm ${user.fullName}. Nhập đúng mã ${user.code} để xác nhận:`)?.trim().toUpperCase();if(!confirmCode)return;if(confirmCode!==user.code.toUpperCase()){notify('error','Mã xác nhận chưa đúng.');return}busyId.value=user.id;try{await softDeleteStudent(runtime(),user.id,confirmCode);notify('success',`Đã xóa mềm ${user.code}; lịch sử vẫn được giữ.`)}catch(e){notify('error',e instanceof Error?e.message:'Không xóa được tài khoản.')}finally{busyId.value=null}}
async function restore(user:DirectoryUser){if(!window.confirm(`Khôi phục tài khoản ${user.code}?`))return;busyId.value=user.id;try{await restoreStudent(runtime(),user);notify('success',`Đã khôi phục ${user.code}.`)}catch(e){notify('error',e instanceof Error?e.message:'Không khôi phục được tài khoản.')}finally{busyId.value=null}}
</script>
<template>
  <div class="page-stack students-page">
    <header class="students-header"><div><span class="page-context"><GraduationCap aria-hidden="true"/>Tài khoản lớp học</span><h1>Học sinh và cán sự</h1><p>Quản lý mã đăng nhập, vai trò và trạng thái tài khoản theo đúng lớp đang chọn.</p></div><AppButton @click="openCreate"><Plus aria-hidden="true"/>Thêm học sinh</AppButton></header>
    <InlineStatus :state="status" :message="statusMessage"/>
    <section class="metrics"><AppCard padding="sm"><span><GraduationCap/>Học sinh</span><b>{{ counts.student }}</b></AppCard><AppCard padding="sm"><span><UsersRound/>Cán sự</span><b>{{ counts.monitor }}</b></AppCard><AppCard padding="sm"><span><UserCheck/>Hoạt động</span><b>{{ counts.active }}</b></AppCard><AppCard padding="sm"><span><UserRoundX/>Đã xóa</span><b>{{ counts.deleted }}</b></AppCard></section>
    <AppCard padding="lg" class="directory-card"><div class="toolbar"><label class="search"><Search aria-hidden="true"/><input v-model="query" placeholder="Tìm theo mã hoặc họ tên" aria-label="Tìm học sinh"></label><label><span>Vai trò</span><select v-model="role"><option value="all">Tất cả</option><option value="student">Học sinh</option><option value="monitor">Cán sự</option></select></label><label><span>Trạng thái</span><select v-model="stateFilter"><option value="active">Đang hoạt động</option><option value="deleted">Đã xóa</option><option value="all">Tất cả</option></select></label></div><div class="directory-meta"><b>{{ visible.length }}/{{ users.length }} tài khoản</b><span>Xóa mềm giữ lịch sử; có thể Khôi phục từ bộ lọc Đã xóa.</span></div><StudentDirectory v-if="visible.length" :users="visible" :busy-id="busyId" @copy="copy" @edit="openEdit" @reset="reset" @delete="remove" @restore="restore"/><div v-else class="empty">Không có tài khoản phù hợp.</div></AppCard>
    <StudentAccountDialog :open="dialogOpen" :user="editing" :classes="classes" :allow-class-change="auth.currentUser?.role==='admin'" :saving="saving" :error="error" @close="dialogOpen=false" @save="save"/>
    <p class="sr-only">Các thao tác hỗ trợ Sao chép mã, Đặt lại mật khẩu, Khôi phục và Xóa mềm tài khoản.</p>
  </div>
</template>
<style scoped>
.students-page{max-width:1500px;margin:0 auto}.students-header{display:flex;align-items:flex-start;justify-content:space-between;gap:18px}.students-header h1{margin:8px 0;font-size:clamp(2rem,4vw,3rem)}.students-header p{margin:0;color:var(--text-muted)}.page-context{display:flex;gap:8px;align-items:center;color:var(--color-primary);font-size:var(--font-size-ui-min);font-weight:900}.page-context svg,.students-header :deep(.app-button svg){width:18px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.metrics :deep(.app-card){display:flex;align-items:center;justify-content:space-between;gap:10px}.metrics span{display:flex;align-items:center;gap:6px;color:var(--text-muted);font-size:var(--font-size-ui-min);font-weight:800}.metrics svg{width:16px}.metrics b{font-size:1.45rem}.directory-card{display:grid;gap:14px}.toolbar{display:grid;grid-template-columns:minmax(240px,1fr) auto auto;gap:10px}.toolbar>label{display:flex;align-items:center;gap:7px;color:var(--text-muted);font-size:var(--font-size-ui-min);font-weight:800}.toolbar select,.search{min-height:44px;border:1px solid var(--border);border-radius:12px;background:var(--surface-raised)}.toolbar select{color:var(--text);padding:0 10px}.search{display:flex;padding:0 10px}.search svg{width:17px}.search input{border:0;outline:0;background:transparent;color:var(--text);width:100%}.directory-meta{display:flex;justify-content:space-between;gap:10px;color:var(--text-muted);font-size:var(--font-size-ui-min)}.empty{text-align:center;padding:28px;color:var(--text-muted)}@media(max-width:820px){.students-header{flex-direction:column}.students-header :deep(.app-button){width:100%}.metrics{grid-template-columns:repeat(2,1fr)}.toolbar{grid-template-columns:1fr}.toolbar>label:not(.search){justify-content:space-between}.directory-meta{flex-direction:column}}
</style>
