<script setup lang="ts">
import { Copy, KeyRound, Pencil, RotateCcw, Trash2 } from 'lucide-vue-next'
import AppButton from '../ui/AppButton.vue'
import RemoteUserAvatar from '../profile/RemoteUserAvatar.vue'
import type { DirectoryUser } from '../../types/legacy'
const props=defineProps<{users:DirectoryUser[];busyId:string|null}>()
const emit=defineEmits<{copy:[user:DirectoryUser];edit:[user:DirectoryUser];reset:[user:DirectoryUser];delete:[user:DirectoryUser];restore:[user:DirectoryUser]}>()
</script>
<template>
  <div class="directory-wrap">
    <table class="directory-table">
      <thead><tr><th>Mã đăng nhập</th><th>Họ tên</th><th>Vai trò</th><th>Trạng thái</th><th>Thao tác</th></tr></thead>
      <tbody><tr v-for="user in users" :key="user.id"><td><div class="code-cell"><b>{{ user.code }}</b><button type="button" class="copy" :aria-label="`Sao chép mã ${user.code}`" @click="emit('copy',user)"><Copy aria-hidden="true"/></button></div></td><td><div class="name-cell"><RemoteUserAvatar :user-id="user.id" :name="user.fullName" :code="user.code" size="sm"/><strong>{{ user.fullName }}</strong></div></td><td>{{ user.role==='monitor'?'Cán sự':'Học sinh' }}</td><td><span v-if="busyId===user.id" class="busy-state"><span class="diamond" aria-hidden="true"></span>Đang xử lý</span><span v-else class="state" :class="{inactive:!user.active}">{{ user.active?'Hoạt động':'Đã xóa' }}</span></td><td><div class="actions"><template v-if="user.active"><AppButton variant="info" :disabled="busyId===user.id" @click="emit('edit',user)"><Pencil aria-hidden="true"/>Sửa</AppButton><AppButton variant="secondary" :disabled="busyId===user.id" @click="emit('reset',user)"><KeyRound aria-hidden="true"/>Mật khẩu</AppButton><AppButton variant="danger" :disabled="busyId===user.id" @click="emit('delete',user)"><Trash2 aria-hidden="true"/>Xóa</AppButton></template><AppButton v-else variant="success" :disabled="busyId===user.id" @click="emit('restore',user)"><RotateCcw aria-hidden="true"/>Khôi phục</AppButton></div></td></tr></tbody>
    </table>
    <div class="directory-cards"><article v-for="user in users" :key="user.id" class="user-card"><header><div class="mobile-identity"><RemoteUserAvatar :user-id="user.id" :name="user.fullName" :code="user.code" size="sm"/><div><b>{{ user.fullName }}</b><small>{{ user.code }} · {{ user.role==='monitor'?'Cán sự':'Học sinh' }}</small></div></div><span v-if="busyId===user.id" class="busy-state">Đang xử lý</span><span v-else class="state" :class="{inactive:!user.active}">{{ user.active?'Hoạt động':'Đã xóa' }}</span></header><div class="mobile-actions"><button type="button" class="copy-code" @click="emit('copy',user)"><Copy/>Sao chép mã</button><template v-if="user.active"><button type="button" :disabled="busyId===user.id" @click="emit('edit',user)"><Pencil/>Sửa</button><button type="button" :disabled="busyId===user.id" @click="emit('reset',user)"><KeyRound/>Mật khẩu</button><button type="button" class="danger" :disabled="busyId===user.id" @click="emit('delete',user)"><Trash2/>Xóa</button></template><button v-else type="button" :disabled="busyId===user.id" @click="emit('restore',user)"><RotateCcw/>Khôi phục</button></div></article></div>
  </div>
</template>
<style scoped>
.directory-wrap{overflow:auto}.directory-table{width:100%;border-collapse:collapse}.directory-table th,.directory-table td{padding:12px 10px;border-bottom:1px solid var(--border);text-align:left;vertical-align:middle}.directory-table tbody tr{transition:background var(--transition-fast)}.directory-table tbody tr:hover{background:color-mix(in srgb,var(--wash-sky) 65%,transparent)}.directory-table th{font-size:var(--font-size-ui-min);color:var(--text-muted);text-transform:uppercase;letter-spacing:.05em}.code-cell,.name-cell,.mobile-identity{display:flex;align-items:center;gap:9px}.code-cell b{padding:5px 8px;border-radius:8px;background:var(--wash-sky);color:var(--color-info);font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.copy{width:34px;height:34px;border:0;border-radius:9px;background:transparent;color:var(--color-info);display:grid;place-items:center}.copy:hover{background:var(--surface-soft)}.copy svg{width:16px}.busy-state{display:inline-flex;align-items:center;gap:7px;color:var(--color-primary);font-size:var(--font-size-ui-min);font-weight:900}.busy-state .diamond{width:9px;height:9px;border-radius:2px;background:currentColor;transform:rotate(45deg);animation:busy-diamond .8s ease-in-out infinite}@keyframes busy-diamond{50%{transform:rotate(135deg) scale(.72);opacity:.55}}.state{display:inline-flex;padding:5px 8px;border-radius:999px;background:color-mix(in srgb,var(--color-success) 12%,var(--surface));color:var(--color-success);font-size:var(--font-size-ui-min);font-weight:900}.state.inactive{background:var(--surface-soft);color:var(--text-muted)}.actions{display:flex;gap:6px;flex-wrap:wrap}.actions :deep(.app-button){min-height:38px;padding:7px 10px;font-size:var(--font-size-ui-min)}.actions :deep(svg){width:15px}.directory-cards{display:none}.user-card{border:1px solid color-mix(in srgb,var(--color-sky) 15%,var(--border));border-radius:14px;padding:13px;background:linear-gradient(145deg,var(--surface-raised),var(--wash-sky))}.user-card header{display:flex;justify-content:space-between;gap:10px}.user-card small{display:block;color:var(--text-muted);margin-top:3px}.mobile-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:12px}.mobile-actions button{min-height:40px;border:1px solid var(--border);border-radius:10px;background:var(--surface-soft);color:var(--text);display:flex;align-items:center;justify-content:center;gap:6px;font-weight:700}.mobile-actions button.danger{color:var(--color-danger)}.mobile-actions svg{width:15px}@media(max-width:820px){.directory-table{display:none}.directory-cards{display:grid;gap:9px}}
</style>
