<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import AppButton from '../ui/AppButton.vue'
import type { DirectoryUser, UserRole } from '../../types/legacy'
const props=defineProps<{open:boolean;user?:DirectoryUser|null;classes?:Array<{id:string;code:string;name:string}>;allowClassChange?:boolean;saving:boolean;error:string}>()
const emit=defineEmits<{close:[];save:[value:{changeCode:boolean;code:string;fullName:string;role:UserRole;classId:string|null;active:boolean;password:string}]}>()
const form=reactive({changeCode:false,code:'',fullName:'',role:'student' as UserRole,classId:'',active:true,password:''})
watch(()=>[props.open,props.user?.id] as const,()=>{form.changeCode=!props.user;form.code=props.user?.code??'';form.fullName=props.user?.fullName??'';form.role=(props.user?.role??'student') as UserRole;form.classId=props.user?.classId??props.classes?.[0]?.id??'';form.active=props.user?.active!==false;form.password=''}, {immediate:true})
const title=computed(()=>props.user?'Sửa tài khoản học sinh':'Thêm học sinh')
function submit(){const code=form.code.trim().toUpperCase(),name=form.fullName.trim();if(!/^[A-Z0-9._-]{2,32}$/.test(code)||!name)return;emit('save',{...form,code,fullName:name,classId:form.classId||null})}
</script>
<template>
  <div v-if="open" class="backdrop" @click.self="emit('close')" @keydown.esc="emit('close')"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="studentAccountTitle"><h2 id="studentAccountTitle">{{ title }}</h2><p class="lead">{{ user?'Chỉ bật đổi mã khi thật sự cần thay mã đăng nhập.':'Tạo tài khoản học sinh/cán sự bằng Edge Function hiện có.' }}</p><div v-if="error" class="error">{{ error }}</div><form @submit.prevent="submit"><label v-if="user" class="toggle"><input v-model="form.changeCode" type="checkbox"><span><b>Đổi mã đăng nhập</b><small>Nếu không bật, mã hiện tại được giữ nguyên.</small></span></label><label>Mã đăng nhập<input v-model="form.code" :disabled="Boolean(user)&&!form.changeCode" maxlength="32" required></label><label>Họ và tên<input v-model="form.fullName" maxlength="120" required></label><label>Vai trò<select v-model="form.role"><option value="student">Học sinh</option><option value="monitor">Cán sự lớp</option></select></label><label v-if="allowClassChange">Lớp<select v-model="form.classId"><option v-for="item in classes" :key="item.id" :value="item.id">{{ item.code }} · {{ item.name }}</option></select></label><label v-if="!user">Mật khẩu tạm<input v-model="form.password" type="password" autocomplete="new-password" placeholder="Để trống để tự sinh"><small>Nếu tự nhập: ít nhất 8 ký tự và có cả chữ lẫn số.</small></label><label v-if="user" class="toggle"><input v-model="form.active" type="checkbox"><span><b>Tài khoản đang hoạt động</b></span></label><div class="actions"><AppButton variant="secondary" @click="emit('close')">Hủy</AppButton><AppButton type="submit" :loading="saving">{{ user?'Lưu tài khoản':'Tạo tài khoản' }}</AppButton></div></form></section></div>
</template>
<style scoped>
.backdrop{position:fixed;inset:0;z-index:110;background:var(--overlay);display:grid;place-items:center;padding:18px}.dialog{width:min(560px,100%);max-height:92vh;overflow:auto;border:1px solid var(--border);border-radius:20px;background:var(--surface-raised);padding:22px;box-shadow:var(--shadow-md)}.dialog h2{margin:0}.lead{color:var(--text-muted);margin:6px 0 16px}.dialog form{display:grid;gap:12px}.dialog label{display:grid;gap:5px;font-weight:800}.dialog input,.dialog select{min-height:44px;border:1px solid var(--border);border-radius:11px;background:var(--surface);color:var(--text);padding:8px 10px}.dialog small{font-weight:500;color:var(--text-muted)}.toggle{grid-template-columns:auto 1fr;align-items:start;background:var(--surface-soft);padding:10px;border-radius:11px}.toggle input{min-height:auto;margin-top:4px}.toggle span{display:grid}.error{color:var(--color-danger);border:1px solid color-mix(in srgb,var(--color-danger) 30%,var(--border));border-radius:10px;padding:9px;background:color-mix(in srgb,var(--color-danger) 7%,var(--surface))}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:5px}@media(max-width:520px){.backdrop{align-items:end;padding:10px}.actions{display:grid;grid-template-columns:1fr}.actions :deep(.app-button){width:100%}}
</style>
