<script setup lang="ts">
import {computed,onMounted,onUnmounted,reactive,ref,watch} from 'vue';
import PageArtwork from '../ui/PageArtwork.vue';
import PageBannerArt from '../ui/PageBannerArt.vue';
import AppCard from '../ui/AppCard.vue';
import AppButton from '../ui/AppButton.vue';
import {homeworkRpc,dateLabel,stateLabels,type HomeworkContext,type HomeworkData,type CatalogSubject,type Notice} from '../../features/homework/api';
import {homeworkTabs,useHomeworkViewStore,resolveHomeworkTab}from '../../features/homework/view-context';

const view=useHomeworkViewStore();
const tab=computed({get:()=>resolveHomeworkTab('admin',view.selectedTab).id,set:(v:string)=>{view.selectedTab=v;}});
const context=ref<HomeworkContext>({classes:[],grades:[6,7,8,9,10,11,12]});
const grade=ref<number|''>(''),classId=ref(''),week=ref('');
const classes=computed(()=>context.value.classes.filter(c=>grade.value===''||c.grade===grade.value));
const weeks=computed(()=>(context.value.weeks||[]).filter(w=>w.school_year_id===context.value.classes.find(c=>c.id===classId.value)?.school_year_id));
interface Audit {id:string;class_id?:string;actor_id:string;event_type:string;created_at:string;before_data:unknown;after_data:unknown}
interface Oversight {metrics:Record<string,number>;hearts:number;history:Array<Notice & {marker?:string;hard_deleted_at?:string}>;audit:Audit[];catalog_audit:Audit[];trash:Notice[];people:Array<{id:string;name:string}>}
const result=ref<Oversight|null>(null),classData=ref<HomeworkData|null>(null),catalog=ref<CatalogSubject[]>([]);
const filters=reactive({actor_id:'',status:'',event_type:'',from:'',to:''});const offset=ref(0);
const loading=ref(false),busy=ref(false),error=ref(''),message=ref('');let generation=0;
const defaults=()=>({id:'',grade:grade.value||7,name:'',short_name:'',icon:'📚',sort_order:0,is_active:true,is_english:false});
const form=reactive(defaults());const target=ref<Notice|null>(null),reason=ref(''),confirmed=ref(false),seed=ref(3),alert=ref('system');
const labels:Record<string,string>={published:'Đã đăng',week:'Đăng trong tuần',pending:'Chờ GV xử lý',deleted:'Đã xóa',contributors:'HS đóng góp'};
const events:Record<string,string>={submit:'Đăng/sửa Báo bài',notice_invalidated:'Xóa Báo bài',notice_restored:'Khôi phục',hard_delete:'Xóa vĩnh viễn',review_keep_existing:'Giữ bài cũ',review_replace_existing:'Thay bằng bài mới',review_keep_both:'Giữ cả hai',reminder:'Nhắc lại',ai_settings:'Cài đặt AI',subject_save:'Môn của lớp',catalog_save:'Danh mục môn khối',group_save:'Nhóm Tiếng Anh',group_assign:'Phân nhóm',settings:'Cấu hình tuyên dương'};
function fail(e:unknown){return e instanceof Error?e.message:'Không thực hiện được thao tác';}
async function load(){const seq=++generation;loading.value=true;error.value='';result.value=null;classData.value=null;catalog.value=[];
 try{const [data,items,local]=await Promise.all([
 homeworkRpc<Oversight>('oversight',classId.value,{grade:grade.value||null,...filters,from:filters.from?`${filters.from}T00:00:00+07:00`:null,to:filters.to?`${filters.to}T00:00:00+07:00`:null,offset:offset.value}),
 homeworkRpc<CatalogSubject[]>('catalog_list','',{grade:grade.value||null}),
 classId.value&&['awards','settings'].includes(tab.value)?homeworkRpc<HomeworkData>('load',classId.value,{week_id:week.value||null}):Promise.resolve(null)]);
 if(seq!==generation)return;result.value=data;catalog.value=items;classData.value=local;
 if(local){seed.value=local.settings.seed_threshold;alert.value=local.alert_level||'system';}
 }catch(e){if(seq===generation)error.value=fail(e);}finally{if(seq===generation)loading.value=false;}}
async function initialize(){loading.value=true;try{context.value=await homeworkRpc<HomeworkContext>('context','');await load();}catch(e){error.value=fail(e);loading.value=false;}}
function resetScope(){generation++;offset.value=0;week.value='';filters.actor_id='';target.value=null;reason.value='';confirmed.value=false;message.value='';Object.assign(form,defaults());}
watch(grade,()=>{classId.value='';resetScope();void load();});
watch(classId,()=>{view.scopeClassId=classId.value;resetScope();void load();});
view.scopeClassId='';
watch([tab,week],()=>{offset.value=0;target.value=null;message.value='';void load();});
watch(()=>({...filters}),()=>{offset.value=0;void load();});
watch(offset,()=>void load());
async function mutation(action:string,payload:Record<string,unknown>,scope=classId.value){if(busy.value)return;busy.value=true;error.value='';message.value='';const seq=generation;
 try{await homeworkRpc(action,scope,payload);if(seq!==generation)return;target.value=null;message.value='Đã lưu thay đổi.';view.refreshVersion++;await load();}catch(e){if(seq===generation)error.value=fail(e);}finally{busy.value=false;}}
async function saveCatalog(){await mutation('catalog_save',{...form,id:form.id||null},'');if(!error.value)Object.assign(form,defaults());}
function editCatalog(s:CatalogSubject){Object.assign(form,{id:s.id,grade:s.grade,name:s.name,short_name:s.short_name,icon:s.icon,sort_order:s.sort_order,is_active:s.is_active,is_english:s.is_english});}
function selectDelete(n:Notice){target.value=n;reason.value='';confirmed.value=false;}
function hardDelete(){if(target.value&&confirmed.value&&reason.value.trim())void mutation('hard_delete',{id:target.value.id,hard_delete_reason:reason.value.trim(),confirm_irreversible:true},target.value.class_id);}
function classLabel(id:string){return context.value.classes.find(c=>c.id===id)?.code||id;}
onMounted(initialize);onUnmounted(()=>{generation++;});
</script>
<template>
<section class="oversight">
 <header class="page-banner oversight-banner"><PageBannerArt tone="lilac"/><div class="page-head-lead"><PageArtwork name="homework" tone="lilac"/><div><p class="eyebrow">QUẢN TRỊ BÁO BÀI</p><h1>Giám sát học tập</h1><p>Tổng quan theo khối, lịch sử theo lớp và danh mục môn chuẩn.</p></div></div></header>
 <AppCard><div class="toolbar"><label>Khối<select v-model.number="grade" :disabled="busy"><option value="">Tất cả khối</option><option v-for="g in context.grades" :key="g" :value="g">Khối {{ g }}</option></select></label><label>Lớp<select v-model="classId" :disabled="busy"><option value="">Tất cả lớp</option><option v-for="c in classes" :key="c.id" :value="c.id">{{ c.code }} · Khối {{ c.grade }}{{ c.active?'':' · Đã khóa' }}</option></select></label><AppButton variant="secondary" :disabled="loading||busy" @click="load">Làm mới</AppButton></div></AppCard>
 <nav class="tabs" aria-label="Các mục Báo bài"><AppButton v-for="t in homeworkTabs('admin')" :key="t.id" :variant="tab===t.id?'primary':'secondary'" :aria-current="tab===t.id?'page':undefined" :disabled="busy" @click="tab=t.id">{{ t.label }}</AppButton></nav>
 <p v-if="error" role="alert" class="error">{{ error }}</p><p v-if="message" role="status">{{ message }}</p><p v-if="loading" role="status">Đang tải dữ liệu theo phạm vi đã chọn…</p>
 <template v-if="result">
 <div v-if="tab==='overview'" class="metrics"><AppCard v-for="(label,key) in labels" :key="key"><strong>{{ result.metrics[key]||0 }}</strong><p>{{ label }}</p></AppCard><AppCard><strong>{{ result.hearts }}</strong><p>Tim hợp lệ</p></AppCard></div>
 <AppCard v-if="tab==='catalog'"><h2>Danh mục môn theo khối</h2><p>Giáo viên kích hoạt các môn này cho lớp được phân công.</p><div class="catalog-list"><button v-for="s in catalog" :key="s.id" @click="editCatalog(s)" :disabled="busy">{{ s.icon }} {{ s.name }} · Khối {{ s.grade }} · {{ s.is_active?'Hoạt động':'Tạm ngưng' }}</button></div>
 <form class="form-grid" @submit.prevent="saveCatalog"><label>Khối<select v-model.number="form.grade" :disabled="!!form.id||busy" required><option v-for="g in context.grades" :key="g" :value="g">{{g}}</option></select></label><label>Tên môn<input v-model="form.name" required maxlength="100" :disabled="busy"></label><label>Tên ngắn<input v-model="form.short_name" maxlength="40" :disabled="busy"></label><label>Biểu tượng<input v-model="form.icon" required maxlength="40" :disabled="busy"></label><label>Thứ tự mặc định<input v-model.number="form.sort_order" type="number" step="1" :disabled="busy"></label><label class="check"><input v-model="form.is_english" type="checkbox" :disabled="busy">Môn Tiếng Anh</label><label class="check"><input v-model="form.is_active" type="checkbox" :disabled="busy">Hoạt động</label><div class="toolbar"><AppButton type="submit" :disabled="busy">{{form.id?'Lưu môn':'Thêm môn'}}</AppButton><AppButton type="button" variant="secondary" :disabled="busy" @click="Object.assign(form,defaults())">Nhập mới</AppButton></div></form></AppCard>
 <AppCard v-if="tab==='history'||tab==='audit'"><h2>{{tab==='history'?'Lịch sử hoạt động':'Nhật ký quản trị'}}</h2><div class="toolbar"><label>{{tab==='history'?'Người đăng':'Người thực hiện'}}<select v-model="filters.actor_id"><option value="">Tất cả</option><option v-for="p in result.people" :key="p.id" :value="p.id">{{p.name}}</option></select></label><label>Từ ngày<input v-model="filters.from" type="date"></label><label>Đến trước ngày<input v-model="filters.to" type="date"></label><label v-if="tab==='history'">Trạng thái<select v-model="filters.status"><option value="">Tất cả</option><option v-for="(label,key) in {...stateLabels,hard_deleted:'Đã xóa vĩnh viễn'}" :key="key" :value="key">{{label}}</option></select></label><label v-else>Hành động<select v-model="filters.event_type"><option value="">Tất cả</option><option v-for="(label,key) in events" :key="key" :value="key">{{label}}</option></select></label></div>
 <template v-if="tab==='history'"><article v-for="n in result.history" :key="n.id"><h3>{{ n.marker||n.title }}</h3><p>{{classLabel(n.class_id)}} · {{n.author_name||n.author_id}} · {{stateLabels[n.status]||n.status}}</p><template v-if="!n.marker"><p>{{n.content}}</p><small>{{dateLabel(n.created_at)}}</small></template><p v-else>Đã xóa vĩnh viễn · {{dateLabel(n.hard_deleted_at!)}}</p></article><p v-if="!result.history.length">Không có hoạt động khớp bộ lọc.</p></template>
 <template v-else><article v-for="e in [...result.audit,...result.catalog_audit]" :key="e.id"><strong>{{e.event_type==='submit'?(e.before_data?'Sửa Báo bài':'Đăng Báo bài'):(events[e.event_type]||e.event_type)}}</strong><p>{{e.class_id?classLabel(e.class_id):'Danh mục khối'}} · {{result.people.find(p=>p.id===e.actor_id)?.name||e.actor_id}} · {{dateLabel(e.created_at)}}</p><details><summary>Chi tiết nhật ký</summary><pre>{{JSON.stringify({before:e.before_data,after:e.after_data},null,2)}}</pre></details></article><p v-if="!result.audit.length&&!result.catalog_audit.length">Không có nhật ký khớp bộ lọc.</p></template>
 </AppCard>
 <AppCard v-if="tab==='awards'"><h2>Tuyên dương theo lớp</h2><p v-if="!classId">Chọn một lớp để xem tuyên dương.</p><template v-else-if="classData"><label>Thời gian<select v-model="week"><option value="">Năm học của lớp</option><option v-for="w in weeks" :key="w.id" :value="w.id">Tuần {{w.week_number}}</option></select></label><div class="form-grid"><section><h3>🐦 Chim sẻ đưa tin</h3><p v-for="p in classData.leaderboard.filter(p=>p.notices>0).sort((a,b)=>a.notice_rank-b.notice_rank)" :key="p.id">#{{p.notice_rank}} · {{p.full_name}} · {{p.notices}} bài</p></section><section><h3>⭐ Ngôi sao dẫn đường</h3><p v-for="p in classData.leaderboard.filter(p=>p.hearts>0).sort((a,b)=>a.heart_rank-b.heart_rank)" :key="p.id">#{{p.heart_rank}} · {{p.full_name}} · {{p.hearts}} tim</p></section><section><h3>🌱 Mầm xanh đóng góp</h3><p v-for="p in classData.leaderboard.filter(p=>p.seed_at)" :key="p.id">{{p.full_name}} · {{p.year_notices}} bài</p></section></div><p v-if="!classData.leaderboard.some(p=>p.notices||p.hearts)">Chưa có đóng góp hợp lệ trong thời gian này.</p></template></AppCard>
<AppCard v-if="tab==='trash'"><h2>Thùng rác theo lớp</h2><p>Xóa vĩnh viễn từng bài đã xóa. Không thể hoàn tác.</p><article v-for="n in result.trash" :key="n.id"><h3>{{n.title}}</h3><p>{{classLabel(n.class_id)}} · {{n.delete_reason}}</p><p>Người gỡ: {{n.deleted_actor_type==='system'?'System':n.deleted_by}}</p><AppButton variant="danger" :disabled="busy" @click="selectDelete(n)">Xóa vĩnh viễn</AppButton></article><p v-if="!result.trash.length">Thùng rác trống trong phạm vi này.</p></AppCard>
 <AppCard v-if="target" role="dialog" aria-label="Xóa vĩnh viễn"><h2>Xóa vĩnh viễn: {{target.title}}</h2><form @submit.prevent="hardDelete"><label>Lý do<textarea v-model="reason" required maxlength="500" :disabled="busy" /></label><label class="check"><input v-model="confirmed" type="checkbox" :disabled="busy">Tôi xác nhận thao tác không thể hoàn tác</label><div class="toolbar"><AppButton type="submit" variant="danger" :disabled="busy||!confirmed||!reason.trim()">Xác nhận xóa vĩnh viễn</AppButton><AppButton variant="secondary" type="button" :disabled="busy" @click="target=null">Hủy</AppButton></div></form></AppCard>
 <AppCard v-if="tab==='settings'"><h2>Cấu hình quản trị</h2><p v-if="!classData">Chọn một lớp để cấu hình tuyên dương.</p><template v-else><form @submit.prevent="mutation('settings',{seed_threshold:seed})"><label>Số bài để nhận Mầm xanh<input v-model.number="seed" type="number" min="1" max="100" required></label><AppButton type="submit" :disabled="busy">Lưu cấu hình</AppButton></form><form @submit.prevent="mutation('alert_settings',{alert_level:alert})"><label>Cảnh báo Admin<select v-model="alert"><option value="system">Chỉ lỗi hệ thống</option><option value="backlog">Lỗi hệ thống + tồn đọng</option><option value="all">Tất cả cảnh báo</option></select></label><AppButton type="submit" :disabled="busy">Lưu cảnh báo</AppButton></form></template></AppCard>
 <div v-if="['history','audit','trash'].includes(tab)" class="toolbar"><AppButton variant="secondary" :disabled="offset===0||loading" @click="offset=Math.max(0,offset-100)">Trang trước</AppButton><span>Trang {{offset/100+1}}</span><AppButton variant="secondary" :disabled="loading||(tab==='history'?result.history.length:tab==='trash'?result.trash.length:Math.max(result.audit.length,result.catalog_audit.length))<100" @click="offset+=100">Trang sau</AppButton></div>
 </template>
</section>
</template>
<style scoped>
.oversight-banner h1{margin:8px 0;font-size:clamp(2rem,4vw,3rem)}.oversight-banner p{margin:0;color:var(--text-muted)}.oversight-banner .eyebrow{color:var(--color-primary);font-weight:850;font-size:var(--font-size-ui-min);letter-spacing:.08em}
.oversight{display:grid;gap:20px;min-width:0}.toolbar,.tabs,.catalog-list{display:flex;flex-wrap:wrap;align-items:end;gap:12px}.tabs{align-items:center}.toolbar label{flex:1;min-width:180px}.form-grid,.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(240px,100%),1fr));gap:16px}.metrics strong{font-size:2rem}label{display:grid;gap:8px;margin-block:10px}.check{display:flex;align-items:center}.check input{width:20px;min-height:20px}input,select,textarea{width:100%;min-width:0;min-height:44px;border:1px solid var(--border);border-radius:var(--radius-md,12px);padding:10px;background:var(--surface-raised);color:var(--text)}.catalog-list button{padding:12px;border:1px solid var(--border);border-radius:12px;background:var(--surface-raised);color:var(--text);text-align:left}article{padding:16px 0;border-bottom:1px solid var(--border);overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere}.error{color:var(--color-danger)}@media(max-width:640px){.toolbar{align-items:stretch}.toolbar label{min-width:0;flex-basis:100%}.tabs :deep(button){white-space:normal}header h1{font-size:1.6rem}}
</style>
