<script setup lang="ts">
withDefaults(defineProps<{variant?:'primary'|'info'|'success'|'warning'|'danger'|'secondary';type?:'button'|'submit'|'reset';loading?:boolean;disabled?:boolean}>(),{variant:'primary',type:'button',loading:false,disabled:false})
</script>
<template><button class="app-button" :class="`is-${variant}`" :type="type" :disabled="disabled||loading"><span v-if="loading" class="diamond-loader" aria-hidden="true"><i></i><i></i><i></i></span><slot /></button></template>
<style scoped>
.app-button{position:relative;isolation:isolate;overflow:hidden;display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:44px;border:1px solid transparent;border-radius:13px;padding:12px 16px;font-weight:800;color:var(--color-on-action);white-space:nowrap;transition:box-shadow var(--transition-fast),background var(--transition-fast),transform var(--transition-fast),border-color var(--transition-fast),filter var(--transition-fast)}
.app-button::before{content:"";position:absolute;z-index:-1;inset:-2px auto -2px -42%;width:32%;transform:skewX(-18deg);background:linear-gradient(90deg,transparent,rgb(255 255 255 / .38),transparent);opacity:0;transition:left .45s ease,opacity .2s ease}.app-button:hover:not(:disabled){box-shadow:0 12px 28px color-mix(in srgb,var(--color-primary) 20%,transparent);transform:translateY(-2px) scale(1.02);filter:saturate(1.06)}.app-button:hover:not(:disabled)::before{left:116%;opacity:1}.app-button:hover:not(:disabled) :deep(svg){transform:translateY(-1px) rotate(-3deg) scale(1.06)}.app-button:active:not(:disabled){box-shadow:var(--shadow-sm);transform:translateY(0) scale(.985)}.app-button:disabled{opacity:.56;cursor:not-allowed}.app-button:focus-visible{outline:3px solid var(--focus-inner);outline-offset:2px;box-shadow:0 0 0 5px var(--focus-ring)}.app-button :deep(svg){transition:transform var(--transition-fast)}
.is-primary{background:var(--gradient-primary)}.is-info{background:linear-gradient(135deg,var(--color-info),var(--color-sky))}.is-success{background:linear-gradient(135deg,var(--color-success),var(--color-mint))}.is-warning{background:linear-gradient(135deg,var(--color-warning),var(--color-sun))}.is-danger{background:linear-gradient(135deg,var(--color-danger),var(--color-coral))}.is-secondary{background:linear-gradient(145deg,var(--surface-raised),var(--wash-violet));color:var(--text);border-color:color-mix(in srgb,var(--color-primary) 15%,var(--border))}
.diamond-loader{display:inline-flex;align-items:center;gap:4px;height:16px}.diamond-loader i{width:7px;height:7px;border-radius:2px;background:currentColor;transform:rotate(45deg);animation:diamondPulse .9s ease-in-out infinite}.diamond-loader i:nth-child(2){animation-delay:.14s}.diamond-loader i:nth-child(3){animation-delay:.28s}@keyframes diamondPulse{0%,100%{transform:rotate(45deg) scale(.62);opacity:.42}50%{transform:rotate(45deg) scale(1);opacity:1}}
@media(prefers-reduced-motion:reduce){.app-button,.app-button::before,.app-button :deep(svg),.diamond-loader i{transition:none!important;animation:none!important}.app-button:hover:not(:disabled),.app-button:active:not(:disabled){transform:none}.diamond-loader i{opacity:.8}}
</style>
